### ISSUE TITLE
Unexpected block frequency - genesis consensus

### ISSUE THREAD

**Issue by HM999** [input-output-hk/shelley-testnet#10]
**Describe the bug**
I bootstrapped a network with a genesis consensus with a 2 second slot time.
```
bootstrap.sh -g -s 2
```
Watching the log, the block were made at a fairly random frequency, 10 seconds, 40 seconds. This carried on for about 10 minutes, after which the node was still running, but never generated another block. (it's 21:27 now and last block was 20:11, i.e. 45 minutes) 

Since my node is the only one on the network, shouldn't my node be making a block every 2 seconds? Or am I not understanding how this works.

Perhaps my operating system is running out of resources somehow, or the machine is too slow to make the 2 second window - but if that was the case, should there not be a big error in the log? It seems like something a node operator would really like to know if it happened.

Or perhaps I just went wrong somewhere.

**To Reproduce**
Straight out of the box, a single faucet-send-money, a single create-account-and-delegate.

**Expected behavior**
As above.

**Additional context**
Linux Ubuntu18. AWS T-Small instance (2GB ram), lots of disk space.

**Comment by HM999** [comment]
nb: stopping the jormungandr process and starting it again, it resumes making blocks in the 10s-40s range.

**Comment by elviejo79** [comment]
In the Ouroboros Genesis protocol the slot duration is variable. 
Using Ouroboros BFT (bootstrap -b) the slot is constant.

**Comment by HM999** [comment]
> In the Ouroboros Genesis protocol the slot duration is variable.
> Using Ouroboros BFT (bootstrap -b) the slot is constant.

But isn't Genesis the one we are meant to be testing?
Also mine totally stopped making blocks, that can't be right.

**Comment by elviejo79** [comment]
You can use both, I was just clarifying that in Genesis, the slot time duration is not constant. :)

About stopping creating blocks... could you please create a new ticket and attach your log file.
that will be useful to analyze thank you!!

**Comment by vincenthz** [comment]
Just to clarify further, slot time duration *ARE* constant, however the frequency of creating blocks is not stable, since the creation of block is now, in genesis-praos, a probability linked to the stake and active slot coefficient.

However clearly in this case, you're hitting the #11 issue.

**Comment by elviejo79** [comment]
@HM999 Are you ok with closing this ticket? 
and continue with the remainder work in #11

**Comment by HM999** [comment]
Sure.
