### ISSUE TITLE
Error while listening on 0.0.0.0:31000

### ISSUE THREAD

**Issue by embraceitandfaceit** [input-output-hk/shelley-testnet#101]
Hi,

Seems the stream failures are gone (for now) but I get another error now:

![image](https://user-images.githubusercontent.com/55874818/66289405-e5f50500-e8dc-11e9-8ab5-6139bd57f53f.png)

Any idea what might cause this problem? I run the node on Linux on a dedicated server

**Comment by NicolasDP** [comment]
looks like you put that same value for the REST API and the Node to Node protocol.

i.e. you might have the same value for:

```yaml
rest:
    listen: 'XXX.XXX.XXX.XXX:PORT_NUMBER'
```

and:

```yaml
p2p:
    public_address: "/ip4/XXX.XXX.XXX.XXX/tcp/PORT_NUMBER"
```

`PORT_NUMBER` needs to be different. For the `rest.listen` put `8080` for example, and leave your `3100` value for the `p2p.public_address`.

**Comment by embraceitandfaceit** [comment]
I think I have another node (from another project) listening at that port number. Can I use whatever portnumber for the cardano node? (for instance 3099 instead of 3100 while setting up the node)

**Comment by dorin100** [comment]
Of course @embraceitandfaceit ! The only limitation is that the port is not already used by another application (check the error message in this case - it should be clear enough...).

**Comment by jakewyo** [comment]
Hi @embraceitandfaceit, we've recently released a new version if you have not yet given it a try: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by dorin100** [comment]
Hi @embraceitandfaceit 

The error message you are receiving is really meaningful. Please make sure that the port you are trying to use is not already used by another app. 

Please reopen if there are any unclarities.
