### ISSUE TITLE
Error fetching genesis block from network

### ISSUE THREAD

**Issue by inti27** [input-output-hk/shelley-testnet#103]
**Describe the bug

I am trying to install the current version of jormungandr (jormungandr-v0.5.6-x86_64-pc-windows-gnu.zip) on a windows 10 VM. once I enter the script to initiate the process I receive the following error, Error fetching genesis block from network
![image](https://user-images.githubusercontent.com/55114776/66423487-d5768480-e9d9-11e9-87a9-b9ef19cece6f.png)

** Prerequisites information
1. `jcli --full-version` output; jcli 0.3.9999 (HEAD-d6e8fabf, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
1. `jormungandr --full-version` output; jormungandr 0.3.9999 (HEAD-d6e8fabf, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
1. What is your Operating system? Windows 10
1. What version of the jormungandr node are you using? windows gnu
1. Did you use jormungandr installer (snap, chocolatey, brew, etc.)? no, followed command line instructions found on this site

**To Reproduce
I followed the instructions on this page https://github.com/input-output-hk/shelley-testnet/wiki/How-to-setup-a-Jormungandr-Networking--node-(--v0.5.0)

**Expected behavior
I expect the genesis block to be created and my node to initialize 

**Additional context
Please add any other context about the problem here.
![image](https://user-images.githubusercontent.com/55114776/66423820-71a08b80-e9da-11e9-84b1-e55c874c7073.png)

**Comment by dorin100** [comment]
Hi @inti27 . The instructions are requring you to use the latest Jromungandr release version. You are using 0.3.9999 when the latest is 0.5.6.

Please follow the instructions in order to use the latest versions and let us know the results. Thanks!

**Comment by inti27** [comment]
Thank you for the feedback @dorin100 I was able to install Jormungandr v0.5.6 and icli. My node starts now but it will not sync. 
![image](https://user-images.githubusercontent.com/55114776/66509421-feae1800-eaa0-11e9-8135-898bc68b339b.png)
I am troubleshooting this issue next. Thanks again.

**Comment by dorin100** [comment]
Now you are experiencing https://github.com/input-output-hk/jormungandr/issues/860 @inti27 . 

I will close this issue as the reported functionality is no longer there. Thank you!
