### ISSUE TITLE
checking the address balance to reciever account not working

### ISSUE THREAD

**Issue by djculli** [input-output-hk/shelley-testnet#104]
PS C:\Users\dj\desktop\jormungandr-v0.5.6-x86_64-pc-windows-gnu> .\jcli rest v0 account get ACCOUNT_ADDRESS -h  http://127.0.0.1:3101/api
error: Invalid value for '<account-id>': account parameter 'ACCOUNT_ADDRESS' isn't a valid address or publickey
PS C:\Users\dj\desktop\jormungandr-v0.5.6-x86_64-pc-windows-gnu>

PS C:\users\dj\desktop\jormungandr-v0.5.6-x86_64-pc-windows-gnu> .\jcli rest v0 utxo get --host http://127.0.0.1:8443/ap
i
failed to make a REST request
  |-> could not connect with node
  |-> http://127.0.0.1:8443/api/v0/utxo: error trying to connect: No connection could be made because the target machine actively refused it. (os error 10061)
  |-> No connection could be made because the target machine actively refused it. (os error 10061)

**Comment by Proxiweb** [comment]
- The first error : you have to give the account address in place of ACCOUNT_ADDRESS

- Second error : It lay be because you have to wait several minutes before the node start accepting rest requests

**Comment by djculli** [comment]
that was the first thing i tried and i got the same error
PS C:\users\dj\desktop\jormungandr-v0.5.6-x86_64-pc-windows-gnu> .\jcli rest v0 account get ed25519_pk1tq3smc27qvsvfwtls
296z7sgreshm3rjcppw07y9ymezmwcamqfsch4frl -h http://127.0.0.1:3101/api
failed to make a REST request
  |-> could not connect with node
  |-> http://127.0.0.1:3101/api/v0/account/58230de15e0320c4b97f828ba17a081e617dc472c042e7f88526f22dbb1dd813: error trying to connect: No connection could be made because the target machine actively refused it. (os error 10061)
  |-> No connection could be made because the target machine actively refused it. (os error 10061)
PS C:\users\dj\desktop\jormungandr-v0.5.6-x86_64-pc-windows-gnu> .\jcli rest v0 account get ca1s4vzxr0ptcpjp39e07pghgt6p
q0xzlwywtqy9elcs5n0ytdmrhvpxyq375e -h http://127.0.0.1:3101/api
failed to make a REST request
  |-> could not connect with node
  |-> http://127.0.0.1:3101/api/v0/account/58230de15e0320c4b97f828ba17a081e617dc472c042e7f88526f22dbb1dd813: error trying to connect: No connection could be made because the target machine actively refused it. (os error 10061)
  |-> No connection could be made because the target machine actively refused it. (os error 10061)
PS C:\users\dj\desktop\jormungandr-v0.5.6-x86_64-pc-windows-gnu>

**Comment by Proxiweb** [comment]
You gave the secret key. The address to use in this call is the account one starting with ca1. It's not really the place to chat, please subscribe to the [ telegram channel](https://t.me/CardanoStakePoolWorkgroup) we will help you.

**Comment by dorin100** [comment]
Hi @djculli . Please do the below steps in order:
1. start the node
2. wait for the node to be started 
3. wait for the node to be synced - https://github.com/input-output-hk/shelley-testnet/wiki/How-do-I-know-that-my-node-is-in-%60sync%60 
4 execute `correct` jcli commands

**Comment by dorin100** [comment]
Thank you @Proxiweb !
