### ISSUE TITLE
CIP : improve jormungandr logger

### ISSUE THREAD

**Issue by Proxiweb** [input-output-hk/shelley-testnet#106]
**USER STORIES**
AS a developer I want to an jormungandr output easy to parse  

**IMPROVEMENT PROPOSAL**
Enhance jormungandr logger :
- in format json, it outputs sometimes several objects on one line, sometimes not. It would be great to always have one object by line
- In plain text, the message part of the line may contains one or more \n newline

**Comment by carl-IOHK** [comment]
Hi Proxiweb 
Agreed that logging could be improved if it is not consistently parsing as you say. I have opened an improvement porposal https://github.com/input-output-hk/jormungandr/issues/918
