### ISSUE TITLE
Generate an address (to receive funds)

### ISSUE THREAD

**Issue by LeaderOfChampions** [input-output-hk/shelley-testnet#110]
I'm unable to figure out how to get past the following in Windows 10 via PowerShell.

Following: [https://iohk.zendesk.com/hc/en-us/articles/360037054073-How-to-Generate-an-address-manually]

![image](https://user-images.githubusercontent.com/35902449/66540668-dd254e80-eae9-11e9-9b0d-723a1488a09b.png)

I'm able to run the below which outputs a long string which I believe is the private key?
./jcli key generate --type=Ed25519Extended > receiver_secret.key

After the above, I'm lost, the following commands are unclear to me. I'm unable to decern if they are clumped into a single command, or if there are 4 other commands that follow, the box is simply confusing. I've been stuck on this step since day one and have tried to run it multiple different ways... 

What is the next command I should run? I'm lead to believe there are more ./jcli commands to provide me with a public key that I put into the faucet, am I wrong?

**Comment by carl-IOHK** [comment]
Hi I also had trouble with something simmilar today. I could create an address usiong a script but not manually by running comands. Based on that I would recomend trying a script instead. What are you trying to do here, and where are that instructions you are following? We have just migrated help content to https://iohk.zendesk.com/hc/en-us/categories/360002383814-Shelley-Networked-Testnet and made some improvements so maybe that will work better?

**Comment by rdlrt** [comment]
I think the "issue" OP is reporting is not being able to find public key, for which he is looking at console instead of the output files created. @LeaderOfChampions when you run those commands as they're shown, your secret and public keys are stored in receiver_secret.key and receiver_public.key.

**Comment by LeaderOfChampions** [comment]
I checked my receiver_public.key file, it is blank?

**Comment by LeaderOfChampions** [comment]
When I run the "next command" nothing happens.

PS D:\jormungandr> **./jcli key to-public > receiver_public.key**                                                           
invalid Bech32
  |-> invalid length
PS D:\jormungandr>

**Comment by LeaderOfChampions** [comment]
When I try the following, I get:

PS D:\jormungandr> ./jcli address account --testing $(cat receiver_public.key)                                          error: The following required arguments were not provided:
    <PUBLIC_KEY>

USAGE:
    jcli.exe address account <PUBLIC_KEY> --prefix <prefix> --testing

For more information try --help
PS D:\jormungandr>

**Comment by rdlrt** [comment]
> PS D:\jormungandr> **./jcli key to-public > receiver_public.key**
1. You cannot simply run an extract of the line.
2. Investigate whether you've set PATH environment variable to include path to jcli and jormungandr. If not, you need ./ for every instance of jcli/jormungandr you refer.

Now, coming to what you're doing:
a. First step was:
./jcli key generate --type=Ed25519Extended > receiver_secret.key
This will create receiver_secret.key with your account's secret key.
b. Second step was *using* the contents of this file as input to generate public key
cat receiver_secret.key | ./jcli key to-public > receiver_public.key
In the quoted example above, you have not mentioned the first half of the syntax, and in earlier attempts, you're probably not checking whether you need ./ or not. The above will populate receiver_public.key with account's public key.
c. Again, third step is *using* output of step above as input to create corresponding key:
./jcli address account --testing $(cat receiver_public.key)
In your case, since your step b was incorrect, it doesnt make sense to try step c.

**Comment by LeaderOfChampions** [comment]
Thank you @rdlrt your steps helped clarify the required steps, very much appreciated.

I anticipate IOHK will break the documentation out further into the individual steps for others being stumped at this stage.

**Comment by rdlrt** [comment]
Not to be rude, but in my honest opinion - we shouldnt be looking at shelley-testnet documentation to learn how OS scripting works - which seems to be happening a lot. That should be part of baseline expectations of running stakepool , especially in testnet phase as [defined](https://testnet.iohkdev.io/cardano/shelley/about/skills-and-requirements/).

Else, we could start at buying hardware or installing OS itself. While its good to get docos accurate, I believe minor details like how to set environment variables in different OS flavours or - or how to use relative paths - should always remain at a 1 line description, in the interest of keeping documents to-the-point.

The baseline closer to mainnet may ofcourse be different, but for now - with the changes expected - it just seems time that could be well spent elsewhere :)

**Comment by LeaderOfChampions** [comment]
Now there is one more person helping with the test net, thats a positive outcome, sorry you feel that way. Again, thank you for your help, I want to push adoption... 

@rdlrt Note, I'll delete this shortly as this is not the forum for such a conversation.
