### ISSUE TITLE
Testnet Install Instructions WIKI GitHub Page is gone or not linked correctly

### ISSUE THREAD

**Issue by WoodDesk** [input-output-hk/shelley-testnet#112]
https://testnet.iohkdev.io/cardano/shelley/about/infrastructure/

The link below to the github instruction page leads to a blank GitHub page. The wiki instructions are not there anymore. please help/fix

To install the Jormungandr networking node, follow [these steps](https://github.com/input-output-hk/shelley-testnet/wiki/How-to-setup-a-Jormungandr-Networking--node-%28v-0.5.0%29).

**Comment by WoodDesk** [comment]
i found the zendesk page - the link on this page:

https://testnet.iohkdev.io/cardano/shelley/about/infrastructure/

...should be redirected to the zendesk page for windows users.  maybe separate links for windows users and linux users
https://iohk.zendesk.com/hc/en-us/articles/360036898353-How-to-Install-Jormungandr-Networking-Windows-

**Comment by carl-IOHK** [comment]
> i found the zendesk page - the link on this page:
> 
> https://testnet.iohkdev.io/cardano/shelley/about/infrastructure/
> 
> ...should be redirected to the zendesk page for windows users. maybe separate links for windows users and linux users
> https://iohk.zendesk.com/hc/en-us/articles/360036898353-How-to-Install-Jormungandr-Networking-Windows-

You are right, thanks, there are a few updates that need to be done on the Shelley Testnet web site that are not done yet. We are working on making those.

**Comment by carl-IOHK** [comment]
> i found the zendesk page - the link on this page:
> 
> https://testnet.iohkdev.io/cardano/shelley/about/infrastructure/
> 
> ...should be redirected to the zendesk page for windows users. maybe separate links for windows users and linux users
> https://iohk.zendesk.com/hc/en-us/articles/360036898353-How-to-Install-Jormungandr-Networking-Windows-

Yes we are making those changes too. Should be done soon. Thanks for poinnting that out.

**Comment by nahern** [comment]
we have made these updates and they will be on the testnet website very soon.
