### ISSUE TITLE
Node crashed network thread 'block2' panicked at 'internal error: entered unreachable code'

### ISSUE THREAD

**Issue by RealD8** [input-output-hk/shelley-testnet#113]
**_Prerequisite Versions information:_**
jcli 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

jormungandr 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

Ubuntu 18.04.3 LTS bionic

jormungandr was installed from binary releases  in github

**_To reproduce_**
Start node and leave it running for about 1 day.

blockRecvCnt: 21883
lastBlockDate: "229.8956"
lastBlockFees: 0
lastBlockHash: 8f737d5e3f6f14e553419b9bcc3715d550067e4e89000f4bff29945d4fad66b2
lastBlockHeight: "80404"
lastBlockSum: 0
lastBlockTime: "2019-10-10T05:03:26+00:00"
lastBlockTx: 0
txRecvCnt: 13
uptime: 77409

**_Error logs_**

Oct 10 07:09:15.944 INFO block successfully applied, date: 229.34012, parent: 8c2100aef25f2f0f3334f114ad15c894ee789548047b658b2985e344879a2485, hash: 8f0b741480906a6e7b43e8a1cd960279ce7a572e2b6fa8aa8c373d42e39610eb, task: block
Oct 10 07:09:15.944 INFO update current branch tip, date: 229.34012, parent: 8c2100aef25f2f0f3334f114ad15c894ee789548047b658b2985e344879a2485, hash: 8f0b741480906a6e7b43e8a1cd960279ce7a572e2b6fa8aa8c373d42e39610eb, task: block
**Oct 10 07:09:15.946 WARN error processing request: Error { code: Internal, cause: BackendError(SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file"))) }, node_id: 15870000297337153516, peer_addr: 18.140.134.230:3000, task: network
Oct 10 07:09:15.946 WARN pulled block validation failed: Error { code: Internal, source: Error { code: Internal, cause: BackendError(SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file"))) } }, node_id: 15870000297337153516, peer_addr: 18.140.134.230:3000, task: network**
Oct 10 07:09:15.946 INFO error connecting to peer, reason: Too many open files (os error 24), peer_addr: 35.184.173.75:3100, task: network
Oct 10 07:09:15.947 INFO client P2P connection closed, node_id: 10520256515201052241, peer_addr: 35.184.173.75:3100, task: network
Oct 10 07:09:16.056 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 51.38.99.171:3250, task: network
Oct 10 07:09:16.056 INFO client P2P connection closed, node_id: 1726906412876557393, peer_addr: 51.38.99.171:3250, task: network
Oct 10 07:09:16.097 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 207.148.81.111:32123, task: network
Oct 10 07:09:16.097 INFO client P2P connection closed, node_id: 4895743244350264142, peer_addr: 207.148.81.111:32123, task: network
Oct 10 07:09:16.097 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 187.36.192.1:3100, task: network
Oct 10 07:09:16.097 INFO client P2P connection closed, node_id: 9899762957404192287, peer_addr: 187.36.192.1:3100, task: network
Oct 10 07:09:16.097 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 187.36.192.1:3100, task: network
Oct 10 07:09:16.097 INFO client P2P connection closed, node_id: 9899762957404192287, peer_addr: 187.36.192.1:3100, task: network
Oct 10 07:09:16.098 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 89.176.103.17:9000, task: network
Oct 10 07:09:16.098 INFO client P2P connection closed, node_id: 6041213913939389472, peer_addr: 89.176.103.17:9000, task: network
Oct 10 07:09:17.249 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 107.150.121.62:3200, task: network
**Oct 10 07:09:17.249 INFO client P2P connection closed, node_id: 18125140645670255114, peer_addr: 107.150.121.62:3200, task: network
thread 'block2' panicked at 'internal error: entered unreachable code', jormungandr/src/blockchain/storage.rs:118:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.**

**_Notes:_**
->The warning before the crash:  Error { code: Internal, cause: BackendError(SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file"  
Could it be related to SQLite creating too many cursors and not closing them lead to that error/warning?
->For the too many open files I will increase my user limit in ulimit.
→I will set the RUST_BACKTRACE= full in my next test run to get more details… and see if this happens again

**Comment by carl-IOHK** [comment]
There was a simmilar error a few days ago but it was fixed so it looks like this is a new one. I will refer this to our dev team.

**Comment by carl-IOHK** [comment]
Hi @RealD8 would you mind if we move this issue to the Support Portal? That way we can link it to the root casue issue and keep track of it better. To do that you could create a ticket here https://iohk.zendesk.com/hc/en-us/requests/new and drop note in this ticket with the ticket number. I would do it for you but I cannot since I do not have your email address.

**Comment by RealD8** [comment]
Hi Carl-IOHK,
Thanks for your support. I have created a ticket as requested (71754) at Zendesk.  
If any further information is needed from my side please let me know.
I understand that this issue can be closed and it can be continued at Zendesk 71754

**Comment by carl-IOHK** [comment]
Thanks @RealD8 that's very considerate of you.
