### ISSUE TITLE
Possible new epoch event bug for leader nodes around epoch boundaries

### ISSUE THREAD

**Issue by hodlonaut** [input-output-hk/shelley-testnet#116]
Observed after converting a few debug log messages to info level on a leader node.

Log output demonstrating the issue:

Oct 12 00:23:22.844 INFO end of epoch, task: leadership
Oct 12 00:23:22.848 INFO Current slot: Slot(32039), **epoch: 89**, task: leadership
Oct 12 00:23:22.848 INFO Within era: EpochPosition { epoch: **Epoch(88)**, slot: EpochSlotOffset(359) }, epoch: 89, task: leadership
Oct 12 00:23:22.848 INFO handling new epoch event, nb_slots: 1, slot start: 359, epoch: 89, task: leadership
Oct 12 00:23:22.849 INFO scheduling new end of epoch, scheduled at: 2019-10-11T15:23:23+00:00, task: leadership
Oct 12 00:23:22.849 INFO Inside query_schedules - logging is working - slot start value is 359, nb slots is 1, epoch: 89, task: leadership
Oct 12 00:23:22.849 INFO Number of leaders is 1, epoch: 89, task: leadership
Oct 12 00:23:22.849 INFO For slot_idx 359 the date_at_slot via leadership is 89.359, epoch: 89, task: leadership
Oct 12 00:23:22.849 INFO Finished the loop of leaders, epoch: 89, task: leadership

Towards the end of the last slot of epoch 88 the above was logged, as you can see the new epoch event handling started while we were still towards the end of slot 359 - because of that the query_schedules was invoked with slot_start value of 359, nb slot = 1 (instead of what I think should have been 0 and 360 for the leadership event generation for new epoch)

As a result, my leader node has no leadership events generated for epoch 89 and sat silent for 2 hours. 

If I were to manually stop it and start it shortly after the above log messages were produced, then I'd observe the query_schedules now being invoked with slot_start = 1 (or something small, early in the epoch), nb slots = (360 - 1) and get my share of leadership events generated for current epoch.

My local workaround for this issue was adding the following snippet of code to handle_new_epoch_event, but i'm sure expert devs will find a better way to address it:

        while within_era.epoch.0 != epoch {
            thread::sleep(Duration::from_secs(1));
            info!(logger, "Having a 1 second sleep because {} is not equal to {}", within_era.epoch.0, epoch);
            current_slot = time_frame.slot_at(&std::time::SystemTime::now()).unwrap();
            info!(logger, "Current slot: {:?}", current_slot);
            within_era = era.from_slot_to_era(current_slot).unwrap();
            info!(logger, "Within era: {:?}", within_era);
        }

**Comment by rinor** [comment]
Since you are digging :) , can you check smth. 

what happens if you set `slots_per_epoch: 1` in both cases with and without your patch!

**Comment by carl-IOHK** [comment]
Hi Guys, I wanted to let you know that we are not actively providing support in this repo any more. We have 
https://iohk.zendesk.com/hc/en-us/requests/new if you want to log an issue or if you want to talk directly to the development team we have https://github.com/input-output-hk/jormungandr/issues.

**Comment by hodlonaut** [comment]
Does that mean this issue will not be looked at, or did it have an entry for it created in IOHK zendesk by the friendly Zendesk admins?

**Comment by carl-IOHK** [comment]
@hodlonaut we would love to create an issue for you in Zendesk but we cannot simply because we do not have your email address. So if you would please create one for us then we can close this issue and work on it there.
