### ISSUE TITLE
As a HODLer/investor using hardware wallet...

### ISSUE THREAD

**Issue by Dmindfuse** [input-output-hk/shelley-testnet#117]
Hi

This question should be in an FAQ (maybe it is, but where?) with regards to the upgrade of the mainnet to fully decentralized Shelley. 

“As a HODLer/Investor waiting for Shelley mainnet storing my ADA on a hardware wallet, do I need to move my ADA off of my hardware wallet into Yoroi or Daedalus between now and the completion of the upgrade of the mainnet to Shelley Decentralized? Is there a risk that I lose my ADA during the mainnet upgrade because I didn’t move my coins off of the hardware wallet?” 

I get this question from some and don’t think they need to worry, but better ask... Cheers.

**Comment by carl-IOHK** [comment]
Hi @Dmindfuse  I wanted to let you know that we are not actively providing support in this repo any more. We have
https://iohk.zendesk.com/hc/en-us/requests/new if you want to log an issue or if you want to talk directly to the development team we have https://github.com/input-output-hk/jormungandr/issues.

**Comment by Dmindfuse** [comment]
Ok. thanks.
