### ISSUE TITLE
Web faucet is not working

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/shelley-testnet#118]
The web faucet is not working - https://testnet.iohkdev.io/shelley/tools/faucet/

**Comment by carl-IOHK** [comment]
@dorin100 any updates on this? I just tried and it seems to work. 

SUCCESS:
Your request has been processed successfully by the faucet and 10000 ADA has been sent to ca1skhag0j0cy79x6y55vzmxvcemcjzlfr4vv4gp7uz7r69kaghj9wccerfmjh. Remember that you will incur 0.0011 ADA transaction processing fees on the testnet.

Please verify the following transaction hash:

34393d71f06dc4b5d095aa5636b2e7847fa9d5a18fffc599345a4d6d14bca653
