### ISSUE TITLE
Error in the overall configuration of the node

### ISSUE THREAD

**Issue by sampsojp** [input-output-hk/shelley-testnet#120]
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: while parsing a block mapping, did not find expected key at line 7 column 42
 |-> while parsing a block mapping, did not find expected key at line 7 column 42

**Comment by sampsojp** [comment]
Created node-config file as per https://iohk.zendesk.com/hc/en-us/articles/360036898153. Installed jormungandr-v0.6.1-x86_64-unknown-linux-gnu.tar.gz on WSL Ubuntu.

**Comment by rdlrt** [comment]
duplicate input-output-hk/jormungandr#971 (among others)
