### ISSUE TITLE
All my Cookies are flushed after deleting the /storage folder.

### ISSUE THREAD

**Issue by JohnDoe1971** [input-output-hk/shelley-testnet#121]
When I delete the storage folder, all cookies are flushed. i am disconnected from Twitter, Gmail, and all logged account. My testnet folder is on D:\ada\storage and not on C:\ where windows is.
It happens every time. Tested it 4 times with same result.

** Technical Support Department

In order to get a faster response to your question, it's better if you post your questions to the Technical Support Team here:

https://iohk.zendesk.com/hc/en-us/requests/new

This support repository is going to be closed soon.

**Comment by carl-IOHK** [comment]
Can you please log a ticket in https://iohk.zendesk.com/hc/en-us/requests/new

This support repository is going to be closed soon.

By the way, please include all the required info for helping you troubleshoot this issue but filling out all the fields in that form.

**Comment by carl-IOHK** [comment]
I'm going to close this ticket
