### ISSUE TITLE
more detail guide installation testnet for Nixos

### ISSUE THREAD

**Issue by altcoiner** [input-output-hk/shelley-testnet#16]
1. how to run testnet in nixos. I could install testnet in Nixos alog with already, but  when I made command "nix-shell --run run-jormungandr" it was not working.
when I succeeded in installation testnet in Nixos, and if I powered off the pc, do I need to input the command once again which I input at the first time to install. 
  
2. Do I need to take a below step also in Nixos. like in Ubuntu as below.

install rustup
Run rustup install stable
Run rustup default stable
Clone this repository: git clone --recurse-submodules https://github.com/input-output-hk/jormungandr
Enter the repository directory: cd jormungandr
install jormungandr: cargo install --path jormungandr
install jcli: cargo install --path jcli

3. what is the next step to make transaction and create delegate in Nixos?

**Comment by disassembler** [comment]
Run nix-shell in jormungandr-nix repo. It will generate genesis block and give instructions to start the node. There's also a Nixos service there you can add to imports too run via systemd.

**Comment by disassembler** [comment]
I've also added binary cache setup to README: https://github.com/input-output-hk/jormungandr-nix/blob/master/README.md#setting-up-nix

**Comment by elviejo79** [comment]
I have created this [video tutorial](https://www.youtube.com/watch?v=JhvRxkBbxMo) and [text tutorial](https://github.com/input-output-hk/shelley-testnet/wiki/Nix-for-stakepool-operators) 

It includes all of the suggestions that @disassembler made in the comments.

Please take a look.

**Comment by altcoiner** [comment]
Hi, Garcia,
Thank you for your great job. I appreciate it.
I succeeded in installation and running.

Bless you





2019년 7월 11일 (목) 오후 10:12, Alejandro Garcia <notifications@github.com>님이 작성:
