### ISSUE TITLE
documentation improvement : empty faucet

### ISSUE THREAD

**Issue by psychomb** [input-output-hk/shelley-testnet#17]
**Not a bug**

Bootstrap -g creates a node/faucet pair where all faucet funds are delegated.
If I empty my faucet to a newly created address without delegation, stop and restart my node, then no additional blocks are made.

**Describe the solution you'd like**

That seems logical (ante-post at least) and expected. However, this might be mentionned somewhere in the documentation.

**Comment by vincenthz** [comment]
@psychomb yes, you're right about the documentation aspect.

so in short, if there's no stake in the system left, then yes the blocks creation grind to a halt forever at the beginning of the new epoch. we are preparing a recovery mechanism for this aspect, which will automatically trigger a BFT recovery phase, but clearly it should be more obvious that it is happening.

Possibly also if it stopped creating block straight away, then it's possible that it is a bug in the stake calculation

**Comment by psychomb** [comment]
I'll try to reproduce it, but it seems that a manual STOP/RESTART is needed to have it happening.

**Comment by psychomb** [comment]
<img width="1349" alt="Screenshot 2019-06-24 at 20 33 15" src="https://user-images.githubusercontent.com/46930715/60042984-5033c200-96bf-11e9-9519-9c809bff3453.png">

As you can see, I could reproduce the behavior. 
Faucet send and included in block 0.179. 
First address is the recipient and second address is the faucet. 

Blockchain halts within 1 block and nothing more during the next ~15 minutes. I therefore stopped my experiment and reported back. No need to stop/restart the node actually.

Cheers,

**Comment by dorin100** [comment]
Thank you @psychomb for finding this. I was able to reproduce it and I opened another issue in order to be tracked and fixed: https://github.com/input-output-hk/jormungandr/issues/576

**Comment by dorin100** [comment]
fixed by https://github.com/input-output-hk/jormungandr/pull/629
