### ISSUE TITLE
Instruction Fixes for Windows Release

### ISSUE THREAD

**Issue by ryanlion26** [input-output-hk/shelley-testnet#18]
Following the instructions on [the self node set up site](https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/) lead to failure for me, but I eventually got it working for the windows release.  Here are my suggestions:

1. Mention GIT Bash as a requirement to run the shell scripts
2. Provide instructions to copy over all the script files, not just bootstrap.  Bootstrap was looking for faucet script.
3. Change instructions from step 11. (poolsecret1.yaml -> pool-secret1.yaml)

**Comment by elviejo79** [comment]
Hi @ryanlion26 

You are correct that video of installing from release is a little obsolete.
I'll update it once we have new instructions to install on windows with Chocolatey
In the mean time I'll post your comments as clarifications on the video.

Just out of curiosity, have you tried to install from source on Windows??
[Install Jormungandr in Windows using WSL](https://youtu.be/315bQKSTdZA)

**Comment by ryanlion26** [comment]
Thanks Alejandro.  Chocolatey sounds like a good solution.

And yes, I've done the WSL method and that works just as expected :)

**Comment by elviejo79** [comment]
Hey @ryanlion26  
Markus Gufler (from Cardano on the Rocks ;-) has created this tutorials for using Jormungandr in Windows wit Power Shell.
https://edu.clio.one/lessons/jormungandr-on-windows/lessons/introduction/

Thought you might  find this tutorials useful :)

In the mean time I'm closing this ticket until we have the Chocolatey installers.
Thanks for reaching out @ryanlion26 and please continue to post questions and suggestions.
