### ISSUE TITLE
Documentation improvement for "Stake Delegation"

### ISSUE THREAD

**Issue by psychomb** [input-output-hk/shelley-testnet#19]
**Not a bug, but a doc issue**
On the Jormungandr stake delegation documentation (https://input-output-hk.github.io/jormungandr/stake_pool/delegating_stake.html), the order of the following calls seems to be wrong.

     jcli transaction finalize CHANGE_ADDRESS --fee-constant 5 --fee-coefficient 2 --fee-certificate 2 --staging tx
     jcli transaction add-certificate $(cat stake_delegation.cert) --staging tx

produces

     adding certificate to finalizing transaction is not valid

On the other hand, typing 

     jcli transaction add-certificate $(cat stake_delegation.cert) --staging tx
     jcli transaction finalize CHANGE_ADDRESS --fee-constant 5 --fee-coefficient 2 --fee-certificate 2 --staging tx

does produce a tx that can be submitted.

**Comment by rinor** [comment]
The `certificate` can be added before `finalize` not after. The docs describe the old behaviour and should be updated. However there is a bug  related to certificate fees https://github.com/input-output-hk/jormungandr/issues/499

**Comment by nahern** [comment]
A PR has been raised to change the order of these examples, as you suggested. Thank you for your feedback,

**Comment by dorin100** [comment]
fixed by https://github.com/input-output-hk/jormungandr/pull/629
