### ISSUE TITLE
video about installation testnet in Nix-os

### ISSUE THREAD

**Issue by altcoiner** [input-output-hk/shelley-testnet#21]
It would be happy, if you add a video how to installation testnet in Nix-os.

**Comment by elviejo79** [comment]
Hi @altcoiner I'm working on this video right as we speak. 
Just a question: How familiar are you with nix? have you used it before?
I'm asking because I don't know how big I should make the introduction to nix before going directly to installing jormungandr.

Thanks for your help

**Comment by altcoiner** [comment]
thank you for reply.
in frank, I am familiar with Ubuntu, but I am trying to used it.
At now, I succeeded in install in Nix-os. and I am trying to make transaction.
Bless you.

**Comment by AcostaJoshua** [comment]
To interject...
I've been able to run testnet nodes on both Ubuntu and MacOS with moderate degrees of success. Been able to start up the node, build blocks, initiate transactions, etc. Things seem to be still a little buggy at this point in the development, but it's a pretty intuitive system when it works. I'm about to  attempt trying my hand at running a node using NixOS on MacOS to continue testing. It seems like many of the members in the Cardano StakePool Best Practice Workgroup are running through NixOS at this point, and I'm sure a comprehensive video including initializing Nix would be helpful for others going forward.

**Comment by cliffc2** [comment]
rick made one for mac, i am noob too. reviewing it now. fixing links.
https://youtu.be/5thgT1QhdfE

his notes:
I will remake this video when I have a faster internet connection. (Edit: Step 4 below may not copy/paste correctly, the link could break) The steps will finish, but the video pretty much ends at the 30 minute mark as my internet slowed way down and the download was taking forever. Here are the steps I am using...

1. Install Nix on OSX (or Linux)
https://nixos.org/nix/

2. Install Nix utilities:
nix-env -iA nixpkgs.git

3. Enable IOHK Binary Cache:
https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exchange-onboarding.md#optional-enable-iohks-binary-cache

4. Install and start Jormungandr with 3 pools:
nix-shell -A shell 

https://github.com/input-output-hk/jo... 

--arg faucetAmounts "[ 1000000000 2000000000 3000000000 ]" --arg numberOfStakePools 2 --arg slot_duration 5 --argstr logger_output gelf --argstr storage "/tmp/jormungandr-storage"  --run run-jormungandr

Use jcli interact:
https://input-output-hk.github.io/jormungandr/introduction.html

**Comment by elviejo79** [comment]
Hi @altcoiner, @AcostaJoshua  and @cliffc2.

Based on your suggestions I created this video tutorial:
https://www.youtube.com/watch?v=JhvRxkBbxMo

Here is the text version
https://github.com/input-output-hk/shelley-testnet/wiki/Nix-for-stakepool-operators

Please take a look and let me know what you think :-)

**Comment by altcoiner** [comment]
Hi, Alejandro Garcia,

It is a great job, and helps me a lot.
I appreciate it.
