### ISSUE TITLE
Sending mulitple transactions crash the node

### ISSUE THREAD

**Issue by sunpwr** [input-output-hk/shelley-testnet#22]
Running Rust Self node in BFT mode:

Trying to send multiple transactions in random amount to a address. It crashed the node after few seconds.

![screenshot](https://user-images.githubusercontent.com/4195173/60195473-acffbb80-982a-11e9-9c0b-650fa6559981.png)

**Comment by dorin100** [comment]
Hi @sunpwr . Can you please provide more details about your scenario?  (like how did you start the node, how many addresses (account or utxo) do you use, do you use any scripts for different operations?)

**Comment by sunpwr** [comment]
Hi dorin100,

The node started by:
>jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml

Using the provided script to send random amount from the faucet account to one receiver account:
>./faucet-send-money.sh $(cat receiver_account.txt) $(( ( RANDOM % 10000 )  + 1000 ))

The error only occurs when trying to send multiple transactions without sleep for few seconds between each transaction.

**Comment by vincenthz** [comment]
three things to note here:

1) if there's a backtrace, please run again after running the following `export RUST_BACKTRACE=1` as indicated
2) the shell scripts are not a great idea for stress testing usually; it's kind of lucky here apparently
3) you can copy paste the useful textual content in a github issue instead of sending screenshot of your terminal .. it's easier for searching

**Comment by sunpwr** [comment]
Hi vincenthz,

Attached are the logs. Thanks.

[node_log.txt](https://github.com/input-output-hk/shelley-testnet/files/3332092/node_log.txt)
[node_log.txt](https://github.com/input-output-hk/shelley-testnet/files/3332093/node_log.txt)

**Comment by sunpwr** [comment]
Hi vincenthz,

Attached are the logs. Thanks!

[event_log.txt](https://github.com/input-output-hk/shelley-testnet/files/3332110/event_log.txt)
[node_log.txt](https://github.com/input-output-hk/shelley-testnet/files/3332111/node_log.txt)

**Comment by dorin100** [comment]
Thank you @sunpwr for letting us know about this issue.  I was able to reproduce it and I opened a separate bug in the main repository - https://github.com/input-output-hk/jormungandr/issues/586

**Comment by gmanroney** [comment]
see linked issue above for latest updates

**Comment by dorin100** [comment]
This was fix and tested through https://github.com/input-output-hk/jormungandr/issues/586.
