### ISSUE TITLE
✗list of delegates encrypted

### ISSUE THREAD

**Issue by smurf123444** [input-output-hk/shelley-testnet#23]
So I get a different output then what is stated in the videos on youtube particularly 
03 Jormungandr send transactions (Shelley testnet)

✗ jcli rest v0 account get <faucet_account> --host "http://127.0.0.1:8443/api"
---
counter: 0
delegation: 23ff409421dcc2fb3043ac73dd037f8b5919499833aec9aeed02f7c870677563
value: 1000000000

**To Reproduce**
1. Go to 'self_node'
2. type jcli rest v0 account get <faucet_account> --host "http://127.0.0.1:8443/api"'
4. See info 
>
counter: 0
delegation: 23ff409421dcc2fb3043ac73dd037f8b5919499833aec9aeed02f7c870677563
//why is it hashed?
value: 1000000000
>
**Expected behavior**
>
counter: 0
delegation: 
- 189
- 118
- 214
- 112
- ETC.
value: 1000000000
>

**Additional context**
I'm a noob

**Comment by dorin100** [comment]
Hi @smurf123444 

In case you generated the files using the bootstrap script, you have a configuration with 1 Faucet that acts also like a Stake Pool (you have a Pool ID generated when executing 'bootstrap -b ... '). So all the faucet funds are delegated as default to the Stake Pool. In this case, the value of the delegation response field when getting the <faucet_account> should be the PoolID (that you can see when running the bootstrap script). 

Check this wiki article for more details - https://github.com/input-output-hk/shelley-testnet/wiki/How-to-delegate-from-a-new-account

**Comment by smurf123444** [comment]
thanks ill close with that
