### ISSUE TITLE
Creating a new delegation certificate failed after using "create-account-and-delegate.sh"

### ISSUE THREAD

**Issue by phamthanhtuan100mc** [input-output-hk/shelley-testnet#26]
**Describe the bug**
I follow these instruction in this link: https://github.com/input-output-hk/shelley-testnet/wiki/How-to-delegate-from-a-new-account and successfully until using **create-account-and-delegate.sh** command,  it auto generate a lot of code like this:

+ FAUCET_SK = ed25519e_sk1dqz9kcqjjmq9vr56wruz4sua2wc0n7gqcw5wszt925ls33qpk4x6x795yeq03g7ejzz4u3uvqucy005lknl8mn8uwkjqtpq705tq9nckh2c9s
+ BLOCK0_HASH=b38f4dbd3792d695b9828f422202219a593e41a97d1a23c0f823524ad81f8d99
+ REST_URL=http://127.0.0.1:8443/api
+ CLI=jcli
+ COLORS=1
+ FEE_CONSTANT=10
+ FEE_CERTIFICATE=0
+ FEE_COEFFICIENT=0
+ ADDRTYPE=--testing
+ STAKE_POOL_ID=378eadea27240fb0cadb28feaaf5221ba69b7ea0e6d07ab281ff1ae099080b73
+ [ 1 -eq 1 ]
+ printf \033[0;32m
+ GREEN=
+ printf \033[0;31m
+ RED=
+ printf \033[0;33m
+ BLUE=
+ printf \033[0m
+ WHITE=
+ [ 0 -ne 0 ]
+ jcli key generate --type=ed25519extended
+ ACCOUNT_SK=ed25519e_sk1yqex8usf9ldfcg5yrykyuys7gpu949wffzr869nm4xkzuc90ddfu77muxf3cufcmnge64p7wu3z39vshchys8a8x970nzcnskx4jlksw43n8a
+ ACCOUNT_SK_FILE=account.prv
+ echo ed25519e_sk1yqex8usf9ldfcg5yrykyuys7gpu949wffzr869nm4xkzuc90ddfu77muxf3cufcmnge64p7wu3z39vshchys8a8x970nzcnskx4jlksw43n8a
+ + jcli key to-public
echo ed25519e_sk1yqex8usf9ldfcg5yrykyuys7gpu949wffzr869nm4xkzuc90ddfu77muxf3cufcmnge64p7wu3z39vshchys8a8x970nzcnskx4jlksw43n8a
+ ACCOUNT_PK=ed25519_pk1etlapmn7txqw882rcgfrmdg4xq6rphmdxedxxe3npfku5g739nzsp663a6
+ echo ed25519_pk1etlapmn7txqw882rcgfrmdg4xq6rphmdxedxxe3npfku5g739nzsp663a6
+ xargs jcli address account --testing
+ ACCOUNT_ADDR=ta1sh90l58w0evcpcuag0ppy0d4z5crgvxld5m95cmxxv9xmj3r6ykv2eghn3h
+ ACCOUNT_COUNTER=0
+ ./faucet-send-money.sh ta1sh90l58w0evcpcuag0ppy0d4z5crgvxld5m95cmxxv9xmj3r6ykv2eghn3h 1000
## Sending 1000 to ta1sh90l58w0evcpcuag0ppy0d4z5crgvxld5m95cmxxv9xmj3r6ykv2eghn3h
discrimination: testing
account: ed25519_pk1etlapmn7txqw882rcgfrmdg4xq6rphmdxedxxe3npfku5g739nzsp663a6
Success!
+ sleep 12
+ echo creating certificate
creating certificate
+ CERTIFICATE_FILE=account_delegation_certificate
+ SIGNED_CERTIFICATE_FILE=account_delegation_certificate.signed
+ jcli certificate new stake-delegation 378eadea27240fb0cadb28feaaf5221ba69b7ea0e6d07ab281ff1ae099080b73 ed25519_pk1etlapmn7txqw882rcgfrmdg4xq6rphmdxedxxe3npfku5g739nzsp663a6 account_delegation_certificate
+ jcli certificate sign account.prv account_delegation_certificate account_delegation_certificate.signed
+ TRANSACTION_FILE=transaction
+ SIGNED_TRANSACTION_FILE=transaction.signed
+ WITNESS_FILE=transaction.witness
+ POST_CERTIFICATE_FEE=10
+ jcli transaction new --staging=transaction
+ jcli transaction add-account --staging=transaction ta1sh90l58w0evcpcuag0ppy0d4z5crgvxld5m95cmxxv9xmj3r6ykv2eghn3h 10
+ cat account_delegation_certificate.signed
+ xargs jcli transaction add-certificate --staging=transaction
+ jcli transaction finalize --staging=transaction
+ jcli transaction id --staging=transaction
+ TRANSACTION_ID=0c1132e3fae484d7c76a57e686ad4ae0faa7f428901b83248f4d702d79452b70
+ jcli transaction make-witness 0c1132e3fae484d7c76a57e686ad4ae0faa7f428901b83248f4d702d79452b70 --genesis-block-hash b38f4dbd3792d695b9828f422202219a593e41a97d1a23c0f823524ad81f8d99 --type account --account-spending-counter 0 transaction.witness account.prv
+ jcli transaction add-witness --staging=transaction transaction.witness
+ jcli transaction seal --staging=transaction
+ + jcli transactionjcli to-message rest --staging v0 transaction message
 post -h http://127.0.0.1:8443/api
Success!
+ echo Now check the proper setting at posted:
Now check the proper setting at posted:
+ echo jcli rest v0 account get ed25519_pk1etlapmn7txqw882rcgfrmdg4xq6rphmdxedxxe3npfku5g739nzsp663a6 -h "http://127.0.0.1:8443/api"
jcli rest v0 account get ed25519_pk1etlapmn7txqw882rcgfrmdg4xq6rphmdxedxxe3npfku5g739nzsp663a6 -h "http://127.0.0.1:8443/api"
+ exit 0

---------------------------------------------

when i use this command: 
jcli rest v0 account get ta1sh90l58w0evcpcuag0ppy0d4z5crgvxld5m95cmxxv9xmj3r6ykv2eghn3h -h  http://127.0.0.1:8443/api

it show:

counter: 0
delegation: ~
value: 1000

**To Reproduce**
1. Go to ./create-account-and-delegate.sh
2. Go to jcli rest v0 account get ta1sh90l58w0evcpcuag0ppy0d4z5crgvxld5m95cmxxv9xmj3r6ykv2eghn3h -h  http://127.0.0.1:8443/api
4. See problem

**Expected behavior**
after this command: jcli rest v0 account get ta1sh90l58w0evcpcuag0ppy0d4z5crgvxld5m95cmxxv9xmj3r6ykv2eghn3h -h  http://127.0.0.1:8443/api

I think it will show like this: 

 counter: 1
 delegation: 378eadea27240fb0cadb28feaaf5221ba69b7ea0e6d07ab281ff1ae099080b73
 value: 990

**Additional context**

os: ubuntu 18.04.2 LTS

I think step **Creating a new delegation certificate** in the auto generate command fail because it cannot being submit to the blockchain, so the delegation  fail

**Comment by dorin100** [comment]
Hi @phamthanhtuan100mc . 

**Issue**: What is happening in your case is that the delegation transaction was not included into a block yet when you check the account status (so the delegation is not yet in place)
**Solution1**: Make sure that you wait for each transaction to be included into a block before checking the results (`jcli rest v0 message logs -h http://127.0.0.1:8443/api`) 
**Solution2**: Use the latest versions of the **bootstrap** and **create-account-and-delegate** scripts -  we updated them in order to make sure that the delegation works (out of thebox) with both BFT and Genesis Praos.

**Comment by phamthanhtuan100mc** [comment]
thank you, but where do i get latest versions of the bootstrap and create-account-and-delegate scripts ?

**Comment by dorin100** [comment]
the scripts can be found here: https://github.com/input-output-hk/jormungandr/tree/master/scripts

**Comment by phamthanhtuan100mc** [comment]
do I need to replace create-account-and-delegate.sh file in self-node folder?

**Comment by dorin100** [comment]
create-account-and-delegate.sh file is automatically createad when you execute bootstrap script (if you have the create-account-and-delegate.shtempl file in the same location with the bootstrap script).

**Comment by dorin100** [comment]
PS: more details for starting the node using the bootstrap script can be found here: https://github.com/input-output-hk/shelley-testnet/wiki/How-to-start-a-self-node

**Comment by phamthanhtuan100mc** [comment]
so, i only have to replace scripts folder and follow instruction in the link below again, right?
https://github.com/input-output-hk/shelley-testnet/wiki/How-to-start-a-self-node

**Comment by dorin100** [comment]
give it a try...

**Comment by phamthanhtuan100mc** [comment]
sorry, when i replace folder **scripts** then using **create-account-and-delegate.sh** again, it return this result:
   ./create-account-and-delegate.sh: 40: ./create-account-and-delegate.sh: function: not found
  1bf3570be50c6e341980f29f2a8a3a87a3d3d3abba3a6573bd4b44593fa396c4
  ./create-account-and-delegate.sh: 42: ./create-account-and-delegate.sh: Syntax error: "}" unexpected

**Comment by dorin100** [comment]
I am sorry but I cannot understand what is happening from the provided details.

Please make sure that you have the latest node version installed and then that you execute the latest version of bootstrap and create-account-and-delegate scripts.

**How to start the node guides:**
- https://github.com/input-output-hk/jormungandr
- https://github.com/input-output-hk/shelley-testnet/wiki/How-to-install-from-source 
- https://github.com/input-output-hk/shelley-testnet/wiki/How-to-start-a-self-node

**How to delegate**
- https://github.com/input-output-hk/shelley-testnet/wiki/How-to-delegate-from-a-new-account
- use `create-account-and-delegate` script after starting the node using the bootstrap script

**Comment by dorin100** [comment]
Closing it as there are more than 3 days from the last interaction. Please reopen it if any clarification is required.
