### ISSUE TITLE
Blocks not syncing between passive node and stake pool node

### ISSUE THREAD

**Issue by lsc3** [input-output-hk/shelley-testnet#27]
**Describe the bug**

Short description:
Not sure what I'm doing wrong. Basically passive node does not dynamically sync with stake pool node. In order sync them, I have to restart the passive node.

Long description:
Have two nodes running.
Node1: staking pool node created with bootstrap.sh (v2.3).
Node2: passive node created using Node1 genesis-block-hash according to instructions at:
https://input-output-hk.github.io/jormungandr/quickstart/02_passive_node.html

At startup, both nodes seem to be in sync because "jcli rest v0 account get ..." requests for preexisting accounts are successful when directed at both nodes.

After starting nodes, a transaction posted to Node1 is successful and icli account requests to Node1 produce the correct account info but "jcli rest v0 account get ..." requests to Node2 produce an error for the same account. Only after restarting Node2 will the account info be produced using a "jcli rest v0 account get ..." request directed at Node2. 

Transactions posted to Node2 remain "pending" and are never incorporated into a block.

**To Reproduce**
1. Start stake pool node.

2. Create account #1 and add funds to it from another account or faucet.  Verify transaction incorporated into block.

3. Create another account (account #2) and leave empty.

4. Start a passive node:
jormungandr --config config.yaml --genesis-block-hash $(cat ./genesis_hash.txt) ... where genesis_hash.txt = hash of stake pool node genesis block hash.

Below is the passive node config.yaml configuration (trusted peers Id 1 = stake pool node):

########
storage: "myhome/bin/node3/jormungandr-storage-test/"

rest:
  listen: "127.0.0.1:8445"
  prefix: "api"

peer_2_peer:
  trusted_peers:
    - id: 1
      address: "/ip4/127.0.0.1/tcp/8299"
  public_id: 3
  public_address: "/ip4/127.0.0.1/tcp/8297"
  topics_of_interests:
    messages: low
    blocks: normal
#######

5. Check account #1 with passive node:
    jcli rest v0 account get <account #1> -h  <passive_node>
    (Returns correct account info)

6. Create a transaction transferring ADA from account #1 account #2.

7. Post transaction to staking pool node address. Verify transaction incorporated into block.
    jcli rest v0 account get <account #2> -h <staking-pool-node>
    (Returns correct account info)

8. Check account #2 on passive node:
    jcli rest v0 account get <transaction> -h <passive node>
    (Returns error)

9. Restart passive node.

10. Check account #2 on passive node again:
    jcli rest v0 account get <transaction> -h <passive node>
    (Return correct info)

**Expected behavior**
Expected transactions posted to the passive node to be sent to the stake pool node and incorporated into blocks. And that this can be verified by sending "jcli rest V0 ..." requests through the passive node.

**Additional context**
Just upgraded to Jormungandr v2.4. Still same problem. Not sure if related but if both stake pool node and passive node are left running for maybe a few minutes to an hour or so (not consistent), the passive node will often start producing error message such as (note: I configured Node1 public_id as 0 in its config.yaml):

Jul 04 19:34:49.658 INFO received a loose block Jul 04 20:55:39.966 INFO received a loose block (63c9744234f8e60f34387bb0b51c18ed62a64910c3b3288ada6448ed195c5b6b), missing parent(s) block(s), task: block
Jul 04 20:55:39.967 WARN block solicitation from 0 failed: TrySendError("..."), task: network
Jul 04 20:55:49.966 INFO received a loose block (300ab606ab6435cfe5e1f31b9042039bc5d99148b64871d8ed08dc66b2396339), missing parent(s) block(s), task: block
Jul 04 20:55:49.966 WARN block solicitation from 0 failed: TrySendError("..."), task: network
Jul 04 20:56:49.972 INFO received a loose block (f5af74870e346fe75215b8d58064cc33a8043cc6a1d1ec29af745dcd6590e051), missing parent(s) block(s), task: block
Jul 04 20:56:49.972 WARN block solicitation from 0 failed: TrySendError("..."), task: network
Jul 04 20:57:29.975 INFO received a loose block (f52e56dae353097416fb7f4f4e69f54c34a05bb6134691daa91f1c37f686928b), missing parent(s) block(s), task: block
Jul 04 20:57:29.975 WARN block solicitation from 0 failed: TrySendError("..."), task: network

**Comment by dorin100** [comment]
Hi @lsc3 . Thank you for raising this complex scenario. 

For the moment we support only 1 single node (we are still working on networking) in any of the modes (Passive, Leader/BFT, Stake Pool/Genesis Praos). Please keep this scenario in mind for when we will provide a cluster.

**Comment by lsc3** [comment]
Thank you.
