### ISSUE TITLE
error running snappy package - genesis file corrupted

### ISSUE THREAD

**Issue by ScofflawPirate** [input-output-hk/shelley-testnet#29]
Greetings - I formatted my server and reinstalled Ubuntu 18.04.
Now attempting to use snapd to install and run self-node.
Upon running this command for the first time: snap install jormungandr && jormungandr.bootstrap -a -l
I get the following error: **installed genesis file corrupted. Invalid type map, expected a sequence at line 1 column 498**
thanks
![Screenshot from 2019-07-07 09-06-06](https://user-images.githubusercontent.com/52602253/60768978-61ee6f80-a098-11e9-8da6-6c62e246a6c5.png)

**Comment by disassembler** [comment]
I've updated jormungandr-nix and generated a new snappy package. Essentially there was a breaking change I didn't catch in my testing because I didn't remove the state dir. The `-l` flag is still broken. I'm looking further into that today.

**Comment by ScofflawPirate** [comment]
I'm just glad is was not on my end. I'll retry when you are ready. thanks!

**Comment by disassembler** [comment]
see https://github.com/input-output-hk/jormungandr/issues/621 for progress on the logging issue.

**Comment by disassembler** [comment]
snappy revision 17 pushed fixing logging.

**Comment by ScofflawPirate** [comment]
It now appears to be working as expected. thank you.
