### ISSUE TITLE
2nd term window error - node rejected request because of invalid parameters

### ISSUE THREAD

**Issue by ScofflawPirate** [input-output-hk/shelley-testnet#30]
Greetings … I have updated Jormungandr self-node Ubuntu server 18.04 using Nix command: nix-shell https://github.com/input-output-hk/jormungandr-nix/archive/master.tar.gz. I am able to run-jormungandr 0.3.0 successfully no issues with logging enabled – see screen shot 1Screenshot from 2019-07-14 11-49-55.
However, when I open a second terminal window to do test transactions, I get the following error for any jcli command: “node rejected request because of invalid parameters”. 
![1Screenshot from 2019-07-14 11-49-55](https://user-images.githubusercontent.com/52602253/61186098-3d157180-a62f-11e9-9833-e9d4ebbab2ad.png)
![2Screenshot from 2019-07-14 11-52-14](https://user-images.githubusercontent.com/52602253/61186103-4f8fab00-a62f-11e9-9dbf-3b872739a152.png)

Thank you.

**Comment by rdlrt** [comment]
You're missing /api in the URL

**Comment by ScofflawPirate** [comment]
Yes, i just tested the suggestion in the other ticket and it worked as expected. this is a duplicate that can be closed. thank you.

**Comment by dorin100** [comment]
thank you @ScofflawPirate
