### ISSUE TITLE
Panic checking balance

### ISSUE THREAD

**Issue by Kevmate** [input-output-hk/shelley-testnet#31]
I started a new chain with 3 fawcetts as in the example. I created a 4th address using: jcli key generate --type Ed25519

I can then check the balance on the 3 genesis addresses, but I get a panic as follows when checking the balance on the 4th address:

user@linux:~$ jcli rest v0 account get $ADDR4 -h  http://127.0.0.1:8443/
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Status(404), "http://127.0.0.1:8443/v0/account/ffbb2d2639d95e0e7eba210a44d65ca8d77df0f321299c6db0b4fb3a0b548302")', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:211
             at src/libstd/panicking.rs:474
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   4: rust_begin_unwind
             at src/libstd/panicking.rs:308
   5: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   6: core::result::unwrap_failed
   7: jcli::jcli_app::rest::v0::V0::exec
   8: jcli::jcli_app::JCli::exec
   9: jcli::main
  10: std::rt::lang_start::{{closure}}
  11: main
  12: __libc_start_main
  13: <unknown>

Is this a bug?

**To Reproduce**
1. Create a brand new chain
2. Add an address using: jcli key generate --type Ed25519. In my case it returned ed25519_sk13pj9rrpp9kx02yvlkzf98jurd6t4tl5cskg5kz7g7f2j7sudgdvs476m99
3. Try to get the details of the address using: jcli rest v0 account get ed25519_sk13pj9rrpp9kx02yvlkzf98jurd6t4tl5cskg5kz7g7f2j7sudgdvs476m99 -h http://127.0.0.1:8443

**Environment
I am running Ubuntu with Nix and Jormangandr and jcli 0.2.3

**Comment by elviejo79** [comment]
The account doesn't actually exist until it has the first transaction in it.

Try sending 1 token to the account and then checking the balance.

**Comment by Kevmate** [comment]
Yes, that worked. I thought maybe it shouldn't have given a panic, since I sometimes get address not found messages if I try an illegal address. Its working though - closing the ticket.
