### ISSUE TITLE
Missing step-by-step guide for creation pool certificate for more people and registration.

### ISSUE THREAD

**Issue by Satuchac** [input-output-hk/shelley-testnet#33]
Hi, 
we are a group of 3 people and we would like to run a pool together. Everybody wants to keep ADA in own wallet. We have just one server and need to create a single pool certificate for that.

Documentation is unclear. There is described only the creation of a pool certificate for one person. We have found the following related documentation issues:

- It is not clear how to create the pool certificate for e.g. 3 people who want to have ADA in own wallet. 

- It is not clear what is the difference between “single”, “group” and “account” address in section 4.2. For what they are used? Which one do we need for our purpose?

- It is unclear by which key the certificate should be signed. I can use priv key for a single person. It works fine. How to do it for more people?

- It is not described how to register or propagate the pool certificate to blockchain.

- The script/faucet send-certificate does not work since it is needed to edit the file and fill some variables. However, there is no documentation on how to do that. I would like to have step by step guide. 

Thank you for your work and support.
Satuchac

**Comment by dorin100** [comment]
Hi @Satuchac . Thank you for your questions. Please find some details below:
1. It is not clear how to create the pool certificate for e.g. 3 people who want to have ADA in own wallet.
- The 3 people can easily delegate their stake to a stake pool (and still keep the ADA in their wallet);
- I am still looking if it is possible that a Stake Pool to be owned/operated by multiple Stake Pool Operators (= the Stake Pool certificate to be signed by multiple Private Keys)

2. It is not clear what is the difference between “single”, “group” and “account” address in section 4.2. For what they are used? Which one do we need for our purpose?
- **Single address** = 1 UTXO (could not delegate its stake into the system)
- **Grouped address** = 1 UTXO (or more) that is attached to an Account in order to be able to delegate its stake (EX: If the Account has a value of 10 and the UTXO has a value of 5, the Account will be able to stake value of 15).
- **Account address** - An address that has its own stake.
- None of these will fit your requirement.

3. It is unclear by which key the certificate should be signed. I can use priv key for a single person. It works fine. How to do it for more people?
- the same as for point no 1

4. It is not described how to register or propagate the pool certificate to blockchain
- The short response is through a transaction. You also have an example - `faucet-send-certificate.sh` script.

5. The script/faucet send-certificate does not work since it is needed to edit the file and fill some variables. However, there is no documentation on how to do that. I would like to have step by step guide.
- the `faucet-send-certificate.sh` script is an example that can be used to send a Certificate to the blockchain (through a transaction that is paid by the Faucet or by an Account - if the ACCOUNT-SOURCE-SK is provided as a second argument).

**Comment by Satuchac** [comment]
Thank you for the response. I would still have some questions. Maybe I still need more clarifications.

- What is the difference between address and account and wallet? What is the exact relation between all of them? Is wallet the same as account? Is that true that the account can have more wallets? Can an account have more addresses as a wallet? 

- I am confused since it is possible to create the pool certificate without any address or account. Then I have signed it by my private key but how it is then connected the pool certificate with any account or stake of the operator? I would expect that the pool certificate is somehow connected with some account or address.

- Would it be possible to extract steps from faucet-send-certificate.sh to step by step guide? At least to understand what happens without parsing the content of the script.

- What is exactly ACCOUNT-SOURCE-SK and where can I take it?

Thank you!
Jarek

**Comment by Satuchac** [comment]
Maybe one more question. How to fulfill these variables? Could you please give me some example or how to where to take values? Mainly fees.

### TEMPLATE
FAUCET_SK="####FAUCET_SK####"
BLOCK0_HASH="####BLOCK0_HASH####"
REST_URL="####REST_URL####"
CLI="####CLI####"
COLORS=####COLORS####
FEE_CONSTANT=####FEE_CONSTANT####
FEE_CERTIFICATE=####FEE_CERTIFICATE####
FEE_COEFFICIENT=####FEE_COEFFICIENT####
ADDRTYPE="####ADDRTYPE####"

**Comment by dorin100** [comment]
There are too many questions... it seems it is necessary to create step-by-step documentation for creating a Stake Pool.

**Comment by Satuchac** [comment]
Yes please. Now I am able to make individual steps. But I am missing full context.

**Comment by dorin100** [comment]
Check the steps for creating a Stake Pool from here: https://github.com/input-output-hk/shelley-testnet/wiki/How-to-create-a-Stake-Pool

**Comment by Satuchac** [comment]
It looks great! It is exactly what I needed :-) I have probably noticed two minor typos.

- In section 3 there is typo. You probably wanted to write: Generate the KES key pair
- In section 6 is probably typo "By providing not providing ...."

If you could find out a way how more accounts could create one pool certificate, allowing more people with own account to operate one pool, it would be awesome. 

Anyway, thank you for the step-by-step guide!
Jarek

**Comment by dorin100** [comment]
Updated the doc. I will let you know, once I will find out if more private keys should be able to sign the Stake Pool certificate.

**Comment by Satuchac** [comment]
Maybe one more question.

jcli certificate new stake-pool-registration \
    --kes-key ${POOL_KES_PK} \
    --vrf-key ${POOL_VRF_PK} \
    --serial 1010101010 > stake_pool.cert

Is there any convention on parameter --serial? Which numbers are valid and what is it good for? Am I right that it is only custom number for an owner?

**Comment by dorin100** [comment]
I will check and came back with a response.

**Comment by Satuchac** [comment]
I went through the whole process and it failed at the end when I wanted to send certificate to blockchain.

This is output of bootstrap script:
---
faucet account: ca1shryfzj0jq350gysnwug8kkc287twjdpsjscmmqymcf5sd425x34cgv8gju
  * public: ed25519_pk1cezg5nusydr6pyymhzpa4kz3ljm5ngvy5xx7cpx7zdyrd24p5dwqwue9cz
  * secret: ed25519e_sk1nzqfsu3gxh5q0qyyfvc7g0hmf7zdrjp4e9n4jlvnmlwu2zyw3425vqkdgl8zcdm046kdzvszaf6duznegalm9lvp4za5zv7ar9ny5ysfnvpv2
  * amount: 1000000000000

pool id: 1b3c0ca64a0c499be03c985a1175ce28e2046fbcc38d74580ff184fe2fdddecd
block-0 hash: 45317455e20b1d1a385660c7cbb422d6fc441fd2c7c5a6efc7a83edffd7d2b7f

To start the node:
  ./jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml
To connect using CLI REST:
  ./jcli rest v0 <CMD> --host "http://127.0.0.1:8443/api"
For example:
  ./jcli rest v0 node stats get -h "http://127.0.0.1:8443/api"
----

I copy/pasted strings to faucet-send-certificate.sh to have it like this:

### TEMPLATE
FAUCET_SK="ca1shryfzj0jq350gysnwug8kkc287twjdpsjscmmqymcf5sd425x34cgv8gju"
BLOCK0_HASH="45317455e20b1d1a385660c7cbb422d6fc441fd2c7c5a6efc7a83edffd7d2b7f"
REST_URL="http://127.0.0.1:8443/api"
CLI="./jcli"
COLORS=1
FEE_CONSTANT=####FEE_CONSTANT####
FEE_CERTIFICATE=####FEE_CERTIFICATE####
FEE_COEFFICIENT=####FEE_COEFFICIENT####
ADDRTYPE="####ADDRTYPE####"

During sending via faucet-send-certificate.sh I got this error:

$ faucet-send-certificate.sh stake_pool.signcert
unrecognized private key bech32 HRP: ca

**Comment by dorin100** [comment]
@Satuchac - you should not change anything inside `faucet-send-certificate.sh` script. All the values inside it are automatically generated when you execute the bootstrap. 

Please follow the steps from the provided document and provide the following logs:
1. bootstrap execution log
2. step by step logs for the steps in the document

**Comment by Satuchac** [comment]
It works fine for me now :-) I was able to send the pool certificate to blockchain. 

I did not put *.shtempl to the directory from which I executed bootstrap.sh. Once I put templates there *.sh scripts have been generated and configured. 

Maybe I would put the info about copying templates as a step 1 before executing bootstrap script.

Scenario prerequisites:
**Copy faucet templates to the same directory where bootstrap.sh is.**
execute bootstrap script - bash bootstrap -g -s 2 -e 50

**Comment by dorin100** [comment]
They are there :) each time you need to execute a script. - https://github.com/input-output-hk/shelley-testnet/wiki/How-to-send-a-Certificate-to-the-blockchain-using-the-faucet-send-certificate.sh-script.

**Comment by dorin100** [comment]
I am still waiting for a response regarding the Stake Pool owned by multiple private keys...

**Comment by dorin100** [comment]
I followed up again with the dev team. I will update here once I receive a response.

**Comment by rinor** [comment]
As of now, my understanding is the following:

`jcli certificate new stake-pool-registration` has also another option called `--owner`. It requires the owner **public key** and can appear **multiple times** based on the number of owners.
Ex from bootstrap file, if we wanted the pool to be owned by both accounts (FAUCET and FIXED) we could do the following (removed ${TMPDIR}/ for readability):
```
$CLI certificate new stake-pool-registration \
    --kes-key ${POOL_KES_PK} \
    --vrf-key ${POOL_VRF_PK} \
    --serial 1010101010 \
    --owner ${FAUCET_PK} \
    --owner ${FIXED_PK} > stake_pool.cert
```
and then sign the certificate by using both (FAUCET and FIXED) **private keys**.
- _stake_key.sk_ contains _FAUCET private key_
- _fixed_key.sk_ contains _FIXED private key_

**1.** Sign **stake_pool.cert** with _FAUCET private key_
`cat stake_pool.cert | $CLI certificate sign stake_key.sk > stake_pool.faucet.signcert`

**2.** Sign **stake_pool.faucet.signcert** with _FIXED private key_
`cat stake_pool.faucet.signcert | $CLI certificate sign fixed_key.sk > stake_pool.signcert`

or in one line
```
cat stake_pool.cert | $CLI certificate sign stake_key.sk | $CLI certificate sign fixed_key.sk > stake_pool.signcert
```
As of now, you can **skip** `--owner` option, and just sign the certificate with multiple private keys ( as done in **1.** and **2.**). 
There is more about this, but I think it will be clarified/defined better once we have the reward mechanism in place.

Please keep in mind that this is just my personal understanding.

**Comment by dorin100** [comment]
The dev team is working hard on network at this point so it might take some more time until they will have time to look into the remaining questions from here.

**Comment by NicolasDP** [comment]
thanks @rinor as usual you are just right, if you want to emulate multiple owners of a stake pool this is the current way.

We are doing some changes to improve the certificates. We will keep you posted.

**Comment by NicolasDP** [comment]
regarding the `--serial` you can put in any value you want, it's a value left to the users to choose whatever they see fit. It's useful if you are operating multiple stake pools. You might sign them with the same owner keys but still want to differentiate one from another. This is one way.

**Comment by Satuchac** [comment]
Hi guys, 

great, I will try --serial option.

Thank you!

Regards,
Jaromir

**Comment by Satuchac** [comment]
It works for us, thank you. You can close it.
