### ISSUE TITLE
DOC ISSUE: Wrong  example for getting settings

### ISSUE THREAD

**Issue by Satuchac** [input-output-hk/shelley-testnet#34]
Hi, 

I have just noticed a minor typo issue in REST documentation:

https://github.com/input-output-hk/jormungandr/blob/master/doc/jcli/rest.md

There is the following example to get settings:

**jcli rest v0 node settings get <options>**

However, for me it it works without **"node"**:

**./jcli rest v0  settings get -h "http://127.0.0.1:8443/api"**

block0Hash: 27b84f51610f4fe8bb435faafb20c0390553a68fe5004e0e3ea0c04e94861d1f
block0Time: "2019-07-25T13:58:32+00:00"
consensusVersion: genesis
currSlotStartTime: "2019-07-26T05:04:56+00:00"
fees:
  certificate: 0
  coefficient: 0
  constant: 10
maxTxsPerBlock: 100

**Comment by rinor** [comment]
Will be fixed once [this](https://github.com/input-output-hk/jormungandr/pull/654/files#diff-968fadac315e834015fb063682d8d730R215) pull request is merged into jormungandr main branch.

**Comment by rinor** [comment]
Fixed. [pull request](https://github.com/input-output-hk/jormungandr/pull/654/files#diff-968fadac315e834015fb063682d8d730R215)  was _just merged_ into jormungandr main branch.
