### ISSUE TITLE
Panic on NonmonotocDate

### ISSUE THREAD

**Issue by Kevmate** [input-output-hk/shelley-testnet#35]
Hi all, I was getting a bit bored sending simple transactions back and forward, so I decided to try an emergency powerdown. I just switched off the computer. When it rebooted I restarted Jormungandr, it all worked. That was at 19:59 on Jul 28th. It then all ran fine with me doing more or less nothing until Jul 29 06:00:54 - 12 hours.

All of a sudden - this:

Jul 29 06:00:54.022 INFO Leader scheduled event, scheduled_at_date: 22590.44, scheduled at_time: SystemTime { tv_sec: 1564376454, tv_nsec: 0 }, sub_task: Leader Task, task: leadership
thread 'block0' panicked at 'called `Result::unwrap()` on an `Err` value: Ledger { source: NonMonotonicDate { block_date: BlockDate { epoch: 22590, slot_id: 44 }, chain_date: BlockDate { epoch: 22590, slot_id: 44 } } }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'leadership0' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError("...")', src/libcore/result.rs:997:5
Jul 29 06:03:24.000 INFO End of epoch, epoch: 22590, sub_task: End Of Epoch Reminder, task: leadership

Then it stopped, it didn't terminate, but also didn't process more blocks. I had to kill it.

I set the environment variable RUST_BACKTRACE=1 and restarted it. It is running again fine. Transactions work. I will watch it.

TBH I'm not sure if this was caused by my "power cut", but it seems to be a fault.

I am running Jormungandr 0.2.3 on a stand alone Ubuntu server, sitting in my server room. I have noticed that you have had a new release now, which is 0.3.1, so I think the best is for me to upgrade to that. In fact, you might decide I should close this issue now since I am running the previous release, but I thought I would post it anyway, just in case.

Thanks

Kevin

**Comment by dorin100** [comment]
@vincenthz - could this be related with https://github.com/input-output-hk/jormungandr/issues/563? If not, what do you think the next step should be for this issue?

**Comment by Kevmate** [comment]
I read the other issue, yes it could be the same thing, but.. for your info.. I am in UK, so I am at GTM+0, so that makes it look like it is not the same thing.

**Comment by Kevmate** [comment]
By the way - would it not be better to set the RUST-BACKTRACE to 1 by default during the test phase? I am having trouble getting this fault to occur again.

**Comment by dorin100** [comment]
@Kevmate - it is ok to close this issue? Considering that the other issue is closed/merged, you should not see the same functionality anymore starting with the next release (> 0.3.1).

**Comment by Kevmate** [comment]
I agree - I am running the new release and it is working - thanks for your time
