### ISSUE TITLE
Sending Coins Windows Server - How

### ISSUE THREAD

**Issue by lightiv** [input-output-hk/shelley-testnet#37]
**Describe the bug**
Following the guide here: https://github.com/input-output-hk/shelley-testnet/wiki/How-to-send-money-from-the-faucet-to-an-account-address

I get to the point of send coins to the created address but there is not a 'faucet_send_money.sk' Windows file.

**To Reproduce**
Look in the jormungandr directory and this file is not found.  I am using release 0.3.2 Windows bootstrap.ps1 to build the self-node

**Expected behavior**
The file to have the file for sending coins under Windows Server

**Comment by dorin100** [comment]
Hi @lightiv . I updated the document by adding some notes in order to make sure that the 3 template files are in the same location with the `bootstrap` file when executing the bootstrap. 

The .sh scripts will be created only if you execute the `bootstrap` script and not the `bootstrap.ps1` one.

**Comment by lightiv** [comment]
Hi thanks,  Isn't bootstrap and the resulting .sh files only for linux?  If this is so, how do Windows Server self-node get the equivalent files?  I am not developer.  20 years ago I had minimal knowledge of Visual Basic and haven't really touched it since.

**Comment by dorin100** [comment]
You can run .sh files also on windows. I prefer to use Git Bash but [here ](https://itsfoss.com/run-linux-commands-in-windows/)you have multiple options.
