### ISSUE TITLE
Jornumgandr-nix node stopped creating blocks

### ISSUE THREAD

**Issue by ADAmint2019** [input-output-hk/shelley-testnet#39]
**Describe the bug**
Installed (with gelf logging) via nix from master Sep 01 13:43.
Last block created was at Sep 02 02:22.
Now simply showing end of epochs.
log_id: 4f094b19-cfa0-437a-a0af-8f08ce17f1b6

**Expected behavior**
Continue to build blocks

**Additional context**
Running on Ubuntu 18.04.3 LTS w/ SSD

**Comment by dorin100** [comment]
Hi @ADAmint2019 . Can you please try to use the latest release and let us know if the issue is still reproducing? If yes, please let us know more details like:
- detailed steps to reproduce (how you installed and started the node, what operations did you do, etc)
- logs

**Comment by ADAmint2019** [comment]
This install occurred yesterday using the following steps:
Set /etc/nix/nix.conf as: 
`substituters = https://cache.nixos.org https://hydra.iohk.io
trusted-substituters =
trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=`

Then opened the shell:
nix-shell --arg faucetAmounts "[ 100000 1234444 34556 ]" --arg numberOfStakePools 2    --argstr logger_output gelf     --argstr storage "/tmp/jormungandr-storage"   https://github.com/input-output-hk/jormungandr-nix/archive/master.tar.gz    --run run-jormungandr

No further commands were run, I simply left the shell running.

Since I left " logger_output gelf  "  in the command and I have provided the log_id above, I am certain that you do have the logs and can confirm there were no other commands run.

If you wish I can redo the steps and see if it occurs again.

**Comment by dorin100** [comment]
Hi @ADAmint2019 . I tried to reproduce this issue using a new VM with Ubuntu 18.04.2 LTS but I was not able to do it. The node created blocks for more than 2 hours. 

We are still trying to figure it out from the logs you send us.

**Comment by ADAmint2019** [comment]
Well, as stated in my ticket, the node was started and ran for just over 12 hours before it stopped creating blocks.
I will start fresh again and see if I can reproduce the 12-13 hour issue. Heck, for all I know it could have been the computer going to sleep that caused it.

Glad that you have the logs, and that this may be of use.

All my best,

Steven Aldrich
(904) 479-5661
steve@fccspro.com <mailto:steve@fccspro.com>
First Coast Computer Services


www.fccspro.com <https://www.fccspro.com/>
First Coast Computer Services is a Service Mark of First Coast Business Consultants, LLC.

**Comment by dorin100** [comment]
Hi @ADAmint2019 . We suspect that it could be caused by computer going to sleep or something like that. We made some changes and we also improved the logging in order to capture these types of events so basically if it will be reproducible in next release, we will have more details. Thank you!

**Comment by dorin100** [comment]
There was a new release - https://github.com/input-output-hk/jormungandr/releases/tag/v0.3.1415.
This issue should not happen anymore or if the computer goes into sleep we should have logs to indicate that.
Please reopen it if you will see it again. Thanks.
