### ISSUE TITLE
JCLI transaction make-witness command returns error

### ISSUE THREAD

**Issue by carlwhiston** [input-output-hk/shelley-testnet#44]
**Error message returned from jcli command  on windows 10**

**To Reproduce**

On your documentation for Jormungandr I was following example commands (see https://input-output-hk.github.io/jormungandr/jcli/transaction.html)

i.e

jcli transaction new > tx

jcli transaction add-input  55762218e5737603e6d27d36c8aacf8fcd16406e820361a8ac65c7dc663f6d1c 0 100 --staging tx

jcli transaction add-account account_address account_funds --staging tx

jcli transaction add-output  ca1qvnr5pvt9e5p009strshxndrsx5etcentslp2rwj6csm8sfk24a2wlqtdj6 50 --staging tx

jcli transaction finalize  ca1q09u0nxmnfg7af8ycuygx57p5xgzmnmgtaeer9xun7hly6mlgt3pjyknplu --fee-constant 5 --fee-coefficient 2 --staging tx

jcli transaction info --fee-constant 5 --fee-coefficient 2 --staging tx

Transaction `0df39a87d3f18a188b40ba8c203f85f37af665df229fb4821e477f6998864273' (finalizing)
  Input:   100
  Output:  89
  Fees:    11
  Balance: 0
 - 55762218e5737603e6d27d36c8aacf8fcd16406e820361a8ac65c7dc663f6d1c:0 100
 + ca1qvnr5pvt9e5p009strshxndrsx5etcentslp2rwj6csm8sfk24a2wlqtdj6 50
 + ca1q09u0nxmnfg7af8ycuygx57p5xgzmnmgtaeer9xun7hly6mlgt3pjyknplu 39

jcli transaction make-witness --genesis-block-hash abcdef987654321... --type utxo txid witness key.prv

it returns with the following error
error: Invalid value for '<transaction-id>': invalid hex encoding for digest value

**Expected behavior**
Command runs and creates a witness file

**Additional context**
It isn't very clear what parameters I should be using and where I obtain them from. The parameter abcdef987654321... clearly should be replaced with something yet the documentation doesn't offer this information.
 
Can you shed any light on the situation. Any help would be gratefully received. 

Many thanks. Carl

**Comment by mmahut** [comment]
Hello @carlwhiston, during ``jcli transaction make-witness ``, please make sure you specify a valid block hash.

**Comment by carlwhiston** [comment]
And where do I find that. Do I generate one some where or is it already in
one of the configuration file? Could you please expand on this please and
give an example. That would be very helpful. Many thanks. Carl

**Comment by elviejo79** [comment]
as @dkijania correctly mentions the genesis-hash is:
`adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770`

the genesis hash is the one where the creators of the blockchain setup the initial configuration.
where they setup the quantity of tokens, the consens protocol, etc.

**Comment by elviejo79** [comment]
@carlwhiston with the correct hash where you able to execute the make-witness command?

**Comment by carlwhiston** [comment]
Hi. Thanks so much for your help. I can try this later today and let you
know. Regards. Carl

**Comment by psychomb** [comment]
Beware of the fee structure before constructing a tx
 
>jcli rest v0 settings get -h http://XXX.XXX.XXX.XXX:XXXX/api

The network will return you this : 
---
block0Hash: adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
block0Time: "2019-02-22T07:53:34+00:00"
consensusVersion: genesis
currSlotStartTime: "2019-09-27T10:32:08+00:00"
fees:
  certificate: 10000
  coefficient: 50
  constant: 1000
maxTxsPerBlock: 255

So you now you know how much you have to pay for a tx fee.

**Comment by carlwhiston** [comment]
Hey. Thanks for your help.

The command you sent totally works i.e 

jcli transaction make-witness 0df39a87d3f18a188b40ba8c203f85f37af665df229fb4821e477f6998864273 --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --type utxo witness key.prv

The witness file is created in my node folder which is great. 

I was able to continue with the example commands until I hit the rest request where I get an error message. Do I need the change the IP address and port? If so where do I get that info? See full example below.

Many thanks, Carl


jcli transaction new > tx
jcli transaction add-input 55762218e5737603e6d27d36c8aacf8fcd16406e820361a8ac65c7dc663f6d1c 0 100 --staging tx
jcli transaction add-output ca1qvnr5pvt9e5p009strshxndrsx5etcentslp2rwj6csm8sfk24a2wlqtdj6 50 --staging tx
jcli transaction finalize ca1q09u0nxmnfg7af8ycuygx57p5xgzmnmgtaeer9xun7hly6mlgt3pjyknplu --fee-constant 5 --fee-coefficient 2 --staging tx
jcli transaction info --fee-constant 5 --fee-coefficient 2 --staging tx

Transaction `0df39a87d3f18a188b40ba8c203f85f37af665df229fb4821e477f6998864273' (finalizing)
 Input: 100
 Output: 89
 Fees: 11
 Balance: 0
 - 55762218e5737603e6d27d36c8aacf8fcd16406e820361a8ac65c7dc663f6d1c:0 100
 + ca1qvnr5pvt9e5p009strshxndrsx5etcentslp2rwj6csm8sfk24a2wlqtdj6 50
 + ca1q09u0nxmnfg7af8ycuygx57p5xgzmnmgtaeer9xun7hly6mlgt3pjyknplu 39


jcli transaction make-witness 0df39a87d3f18a188b40ba8c203f85f37af665df229fb4821e477f6998864273 --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --type utxo witness key.prv

jcli transaction add-witness witness --staging tx
jcli transaction seal --staging tx
jcli transaction to-message --staging tx > txmsg
jcli rest v0 message post -f txmsg --host http://127.0.0.1:8443/api (FALLS OVER with below error)


failed to make a REST request
 |-> could not connect with node
 |-> http://127.0.0.1:8443/api/v0/message: error trying to connect: No connection could be made because the target machine actively refused it. (os error 10061)
 |-> No connection could be made because the target machine actively refused it. (os error 10061)

     On Friday, 27 September 2019, 10:09:13 BST, Dariusz Kijania <notifications@github.com> wrote:  
 
 
Hi,

Assuming that genesis block hash is equal to: adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 

I believe that below commands should work:

for utxo input:
jcli transaction make-witness 0df39a87d3f18a188b40ba8c203f85f37af665df229fb4821e477f6998864273 --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770  --type utxo witness key.prv
for account:
jcli transaction make-witness 0df39a87d3f18a188b40ba8c203f85f37af665df229fb4821e477f6998864273 --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770  --type account --account-spending-counter 0 witness key.prv

**Comment by dkijania** [comment]
@carlwhiston 
How u started node ? 
By using single command (e.g. `jormungandr --trusted-peers xxxxx --genesis-block-hash`) or by providing config.yaml file (e.g. `jormungandr --config config.yaml --genesis-block-hash xxxxx`) ?

There might be a bug which causes that if you start jormungandr using first method rest api can be not accessible. If yes, you can run it in second fashion with config.yaml file like below:

```
log:
  level: info
rest:
  listen: "127.0.0.1:9000"
p2p:
  public_address: /ip4/MY_PUBLIC_IP/tcp/3000
  listen_address: /ip4/MY_PRIVATE_IP/tcp/3000
  trusted_peers: [/ip4/TRUSTED_PEER1/tcp/3000,
                  /ip4/TRUSTED_PEER2/tcp/3000,
                  /ip4/TRUSTED_PEER2/tcp/3000,
                  /ip4/TRUSTED_PEER3/tcp/3000,
                  /ip4/TRUSTED_PEER4/tcp/3000]
  topics_of_interest:
    messages: high
    blocks: high
--
```

**Comment by carlwhiston** [comment]
Hey. Thanks for your help.

I have successfully got the make-witness command to run. I was missing the transaction reference (address / UTXO) 

I tried to run the command you sent, filling in the parameters from the example in the transaction command documentation - https://input-output-hk.github.io/jormungandr/jcli/transaction.html?highlight=rest#send-the-transaction

So my command looks like this

jcli rest v0 settings get -h http://127.0.0.1:8443/api

BUT it returns the below error. 

failed to make a REST request
 |-> could not connect with node
 |-> http://127.0.0.1:8443/api/v0/settings: error trying to connect: No connection could be made because the target machine actively refused it. (os error 10061)
 |-> No connection could be made because the target machine actively refused it. (os error 10061)


Can you help? Maybe I have the wrong parameters? If so then where could I find them?

Many thanks. Carl
     On Friday, 27 September 2019, 11:33:27 BST, Malick Mbengue <notifications@github.com> wrote:  
 
 
Beware of the fee structure before constructing a tx


jcli rest v0 settings get -h http://XXX.XXX.XXX.XXX:XXXX/api


The network will return you this :

block0Hash: adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
block0Time: "2019-02-22T07:53:34+00:00"
consensusVersion: genesis
currSlotStartTime: "2019-09-27T10:32:08+00:00"
fees:
certificate: 10000
coefficient: 50
constant: 1000
maxTxsPerBlock: 255

So you now you know how much you have to pay for a tx fee.

**Comment by carlwhiston** [comment]
Hi.

I am starting the node with the bootstrap script from the powershell console as administrator. So the script uses the \config\config.yaml file

I copied in the below content as suggested but then the node produces an error when I try to run it (see below)

Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: p2p.public_address: invalid value: string "/ip4/MY_PUBLIC_IP/tcp/3000", expected Multiaddr (example: /ip4/192.168.0.1/tcp/443) at line 7 column 19
 |-> p2p.public_address: invalid value: string "/ip4/MY_PUBLIC_IP/tcp/3000", expected Multiaddr (example: /ip4/192.168.0.1/tcp/443) at line 7 column 19

     On Friday, 27 September 2019, 17:38:11 BST, Dariusz Kijania <notifications@github.com> wrote:  
 
 
@carlwhiston
How u started node ?
By using single command (e.g. jormungandr --trusted-peers xxxxx --genesis-block-hash) or by providing config.yaml file (e.g. jormungandr --config config.yaml --genesis-block-hash xxxxx) ?

There might be a bug which causes that if you start jormungandr using first method rest api can be not accessible. If yes, you can run it in second fashion with config.yaml file like below:
log:  level: inforest:  listen: "127.0.0.1:9000"p2p:  public_address: /ip4/MY_PUBLIC_IP/tcp/3000  listen_address: /ip4/MY_PRIVATE_IP/tcp/3000  trusted_peers: [/ip4/TRUSTED_PEER1/tcp/3000,                  /ip4/TRUSTED_PEER2/tcp/3000,                  /ip4/TRUSTED_PEER2/tcp/3000,                  /ip4/TRUSTED_PEER3/tcp/3000,                  /ip4/TRUSTED_PEER4/tcp/3000]  topics_of_interest:    messages: high    blocks: high--

**Comment by dkijania** [comment]
@carlwhiston MY_PRIVATE_IP is just a placeholder which you should fill your ip (like: 192.168.0.2:3100) the same for all placeholder. see example here:

https://github.com/input-output-hk/shelley-testnet/issues/82

**Comment by jakewyo** [comment]
Hi @carlwhiston you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by carlwhiston** [comment]
Thank you, I will do. Also can I say that when I downloaded the Daedalus wallet on Windows 10 it took over 48 hours to synchronise with the block. It took up pretty much most of my computers cpu so it was unusable for that period. Does that sound right? Thanks. Carl
     On Tuesday, 8 October 2019, 17:19:45 BST, jakewyo <notifications@github.com> wrote:  
 
 
Hi @carlwhiston you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by jakewyo** [comment]
@carlwhiston Although the synchronization process can take a few hours to complete, 48 hours doesn't seem right. Please submit a request to our support team from the Daedalus **Help** menu in the application. Please also be sure to attach your logs. We will begin investigating immediately.

**Comment by carl-IOHK** [comment]
@carlwhiston so did @dkijania's advice work? Did you resolve the issue raised in this ticket? If so we would like to close the ticket.

**Comment by carlwhiston** [comment]
Yes it works good now. Thank you and yes you can close the ticket. Thanks
for your help. Carl
