### ISSUE TITLE
New UTXO tx not accepted on the testnet

### ISSUE THREAD

**Issue by mmahut** [input-output-hk/shelley-testnet#45]
**Describe the bug**

I'm trying to send a UTXO transition, but after submitting it, it's just pending.

**To Reproduce**
1. Request funds from faucet - this is working fine, you can see it under ```90a3d5f6c294770b88bfa9f8bb939a436e39d8640ccf9eedb02fa0807186bbd7```
2. Construct and send my UTXO transation.
```# cat txmsg 
00bf020102000000003a3529440090a3d5f6c294770b88bfa9f8bb939a436e39d8640ccf9eedb02fa0807186bbd78328eb3526eeee2ac366dff2c2f3f4db941184f0f427a2b1a42a2f5d1250ab3c0f000000000000053983868d801ba2f779cd0b5a2e7417bb58bbeeb6e4b29c125b7f3faaf8debaa48ba20000003a35293ebc016c97c080372ecbf1aa33cc6da7aee73c0bed210842209e128cc8bd3e63a9eabc1eee853a07aeb2a5e7f600000c13444536517f42c80c8df87b7e5697b6923e0d
```
```
# jcli rest v0 message post -f txmsg --host http://127.0.0.1:8443/api
2739270e48b86d185b0e5745dd9d1f2874e93b6be7b6e7d836dbffe31bfb2dbc
```

It is accepted, however forever in pending status.

```
# jcli rest v0 message logs -h http://127.0.0.1:8443/api
---
- fragment_id: 2739270e48b86d185b0e5745dd9d1f2874e93b6be7b6e7d836dbffe31bfb2dbc
  last_updated_at: "2019-09-27T07:21:17.226054627+00:00"
  received_at: "2019-09-27T07:21:17.226054544+00:00"
  received_from: Rest
  status: Pending
```

**Expected behavior**
Transaction is accepted into a block and processes.

**Additional context**
Easy to reproduce, please see attached log.
[transation.log](https://github.com/input-output-hk/shelley-testnet/files/3661498/transation.log)

**Comment by mmahut** [comment]
Duplicate of #844

**Comment by elviejo79** [comment]
@mmahut we will continue to monitor this problem in  input-output-hk/jormungandr#844.
