### ISSUE TITLE
Balance issue

### ISSUE THREAD

**Issue by PierreLz** [input-output-hk/shelley-testnet#46]
**Describe the bug**
Wong ADA Balance.

**Expected behavior**

1/ I followed every steps from the begining and executed the node.
2/ Then I generated an address with success.
3/ Made a request from the faucet and told me 250 000 ADA were sent.
4/ Checked the balance: 

jcli rest v0 account get $(cat receiver_account.txt) -h  http://127.0.0.1:3101/api
---
counter: 0
delegation:
  pools: []
value: 250000000000`

**Additional context**
Plus, would like to send back the tokens from the faucet but I don't know how to do it.

**Comment by NicolasDP** [comment]
It's because the API display values in `Lovelace`.

**Comment by PierreLz** [comment]
Allright, it makes sense thank you. How about to send back the tokens ?
