### ISSUE TITLE
Error while parsing the node configuration file

### ISSUE THREAD

**Issue by WenXian15** [input-output-hk/shelley-testnet#47]
I had the following error when executing the node on Windows PowerShell, the node-config.yaml used is identical to the one given in Linux/Mac section.  

`Error in the overall configuration of the node
Error while parsing the node configuration file: p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 13 column 7`

**Comment by dorin100** [comment]
@WenXian15 - please provide more details like the exact files and commands you used + the entire log.

**Comment by WenXian15** [comment]
> @WenXian15 - please provide more details like the exact files and commands you used + the entire log.

I followed exactly step 1-5 on [https://github.com/input-output-hk/shelley-testnet/wiki/How-to-setup-a-Jormungandr-Networking--node-%28v-0.5.0%29](url).  Create a configuration file as node-config.yaml using notepad++ with the following script 

---
log:
  format: plain
  level: debug
  output: stderr
p2p:
  listen_address: /ip4/0.0.0.0/tcp/3100
  public_address:
  topics_of_interest:
    blocks: high
    messages: high
  trusted_peers:
    - /ip4/3.123.177.192/tcp/3000
    - /ip4/52.57.157.167/tcp/3000
    - /ip4/3.123.155.47/tcp/3000
    - /ip4/3.115.57.216/tcp/3000
    - /ip4/3.112.185.217/tcp/3000
    - /ip4/18.139.40.4/tcp/3000
    - /ip4/18.140.134.230/tcp/3000
rest:
  listen: "127.0.0.1:3101"
storage: /tmp/jormungandr

And execute the node 
`jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info`

the following error is received after executing the node 
`Error in the overall configuration of the node
Error while parsing the node configuration file: p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 13 column 7`

**Comment by dorin100** [comment]
Can you please add the trusted peers beetwen [] like below?

  trusted_peers: [/ip4/3.123.177.192/tcp/3000,
                  /ip4/3.123.155.47/tcp/3000,
                  /ip4/52.57.157.167/tcp/3000,
                  /ip4/3.112.185.217/tcp/3000,
                  /ip4/18.140.134.230/tcp/3000,
                  /ip4/18.139.40.4/tcp/3000,
                  /ip4/3.115.57.216/tcp/3000]

**Comment by WenXian15** [comment]
> Can you please add the trusted peers beetwen [] like below?
> 
> trusted_peers: [/ip4/3.123.177.192/tcp/3000,
> /ip4/3.123.155.47/tcp/3000,
> /ip4/52.57.157.167/tcp/3000,
> /ip4/3.112.185.217/tcp/3000,
> /ip4/18.140.134.230/tcp/3000,
> /ip4/18.139.40.4/tcp/3000,
> /ip4/3.115.57.216/tcp/3000]

This error shows up after the change
`Error in the overall configuration of the node
Error while parsing the node configuration file: while parsing a block mapping, did not find expected key at line 12 column 3`

**Comment by dorin100** [comment]
Ok, one step further. 

The below node configuration should finally work. Please update your public IPv4 address for the `public_address` parameter.

```
rest:
  listen: "127.0.0.1:3101"
p2p:
  listen_address: /ip4/0.0.0.0/tcp/3100
  public_address: /ip4/YOUR_PUBLIC_IPv4_ADDRESS/tcp/3100
  trusted_peers: [/ip4/3.123.177.192/tcp/3000,
                  /ip4/3.123.155.47/tcp/3000,
                  /ip4/52.57.157.167/tcp/3000,
                  /ip4/3.112.185.217/tcp/3000,
                  /ip4/18.140.134.230/tcp/3000,
                  /ip4/18.139.40.4/tcp/3000,
                  /ip4/3.115.57.216/tcp/3000]
    topics_of_interest:
      blocks: high
      messages: high
```

**Comment by WenXian15** [comment]
> Ok, one step further.
> 
> The below node configuration should finally work. Please update your public IPv4 address for the `public_address` parameter.
> 
> ```
> rest:
>   listen: "127.0.0.1:3101"
> p2p:
>   listen_address: /ip4/0.0.0.0/tcp/3100
>   public_address: /ip4/YOUR_PUBLIC_IPv4_ADDRESS/tcp/3100
>   trusted_peers: [/ip4/3.123.177.192/tcp/3000,
>                   /ip4/3.123.155.47/tcp/3000,
>                   /ip4/52.57.157.167/tcp/3000,
>                   /ip4/3.112.185.217/tcp/3000,
>                   /ip4/18.140.134.230/tcp/3000,
>                   /ip4/18.139.40.4/tcp/3000,
>                   /ip4/3.115.57.216/tcp/3000]
>     topics_of_interest:
>       blocks: high
>       messages: high
> ```

The same error shows up again 
`Error while parsing the node configuration file: p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer`

**Comment by Chris-Graffagnino** [comment]
@dorin100 The wiki has a typo (missing a space).
Currently is `trusted_peers:[/ip4/3.123.177.192/tcp/3000,`.
Should be `trusted_peers: [/ip4/3.123.177.192/tcp/3000,`

**Comment by pheelLikeWater** [comment]
Im getting the same error....

Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 9 column 19
 |-> p2p.trusted_peers[0]: invalid type: string "/ip4/3.123.177.192/tcp/3000", expected struct TrustedPeer at line 9 column 19

With the following config.

p2p:
  public_address: "/ip4/X.X.X.X/tcp/8299"
  listen_address: "/ip4/127.0.0.1/tcp/8299"
  trusted_peers: [/ip4/3.123.177.192/tcp/3000,
                  /ip4/3.123.155.47/tcp/3000,
                  /ip4/52.57.157.167/tcp/3000,
                  /ip4/3.112.185.217/tcp/3000,
                  /ip4/18.140.134.230/tcp/3000,
                  /ip4/18.139.40.4/tcp/3000,
                  /ip4/3.115.57.216/tcp/3000]
  topics_of_interest:
    messages: high
    blocks: high

**Comment by lukue** [comment]
I got the same issue.

Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: p2p.trusted_peers[0].id: Odd number of digits at line 8 column 10
 |-> p2p.trusted_peers[0].id: Odd number of digits at line 8 column 10

Followed this instruction: https://iohk.zendesk.com/hc/en-us/articles/360036898153#article-comments

**Comment by dorin100** [comment]
@lukue - something from your node configuration is not correct; please open a ticket in zendesk in order to get proper help and be redirected to correct configurations depending on the testnet you are trying to use! cheers.
