### ISSUE TITLE
Testing Network Connectivity page of testnet documentation does not interpret Markdown

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/shelley-testnet#48]
Last example at page [Testing Network Connectivity](https://testnet.iohkdev.io/cardano/shelley/get-started/testing-network-connectivity/) of testnet documentation does not interpret the entered markdown, should be updated to HTML.

`jcli rest v0 utxo get --host [http://127.0.0.1:8443/api](http://127.0.0.1:8443/api)`

**Comment by dorin100** [comment]
fixed. thank you @mark-stopka !
