### ISSUE TITLE
nix-shell installs jorgumndr ver 0.1.0

### ISSUE THREAD

**Issue by elviejo79** [input-output-hk/shelley-testnet#5]
**Describe the bug**
when installing through nix-shell rust self_node it installs the version 0.1.0
and the newest one is 0.2.1

**To Reproduce**
1. Install like this: nix-shell https://github.com/input-output-hk/jormungandr-nix/archive/d868493c7c12568cee08eb975c28fe8d4b6e0c89.tar.gz

**Expected behavior**
We want the latest jormungandr release.

**Additional context**

this is what message logs returns

```
agarciafdz@agarciafd-lg:~/jor-test/self_node$ jcli rest v0 message logs -h http://127.0.0.1:8443/api
---
[]
```

[my_node.log](https://github.com/input-output-hk/shelley-testnet/files/3294984/my_node.log)

**Comment by disassembler** [comment]
Jormungandr-nix now has 0.2.1 as well as a master version it's currently using as defualt.
