### ISSUE TITLE
error while parsing the node

### ISSUE THREAD

**Issue by djculli** [input-output-hk/shelley-testnet#50]
this was the error i recieved when trying to execute the node

PS C:\users\dj\desktop\jormungandr-v0.5.2-x86_64-pc-windows-gnu> .\jormungandr --config node-config.yaml --genesis-block
-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: while parsing a block mapping, did not find expected key at line 12 column 3
 |-> while parsing a block mapping, did not find expected key at line 12 column 3
PS C:\users\dj\desktop\jormungandr-v0.5.2-x86_64-pc-windows-gnu>

**Comment by rinor** [comment]
Please attach `node-config.yaml` or paste the content within code blocks to keep formating.

**Comment by djculli** [comment]
---
log:
  format: plain
  level: info
  output: stderr
p2p:
  listen_address: /ip4/0.0.0.0/tcp/3100
  public_address:
  topics_of_interest:
    blocks: high
    messages: high
  trusted_peers:[/ip4/3.123.177.192/tcp/3000,
                  /ip4/3.123.155.47/tcp/3000,
                  /ip4/52.57.157.167/tcp/3000,
                  /ip4/3.112.185.217/tcp/3000,
                  /ip4/18.140.134.230/tcp/3000,
                  /ip4/18.139.40.4/tcp/3000,
                  /ip4/3.115.57.216/tcp/3000]
rest:
  listen: "127.0.0.1:3101"
storage: /tmp/jormungandr

**Comment by rinor** [comment]
there is a missing space at `trusted_peers:[` it ha to be `trusted_peers: [`
fix it or copy paste the following
```
log:
  format: plain
  level: info
  output: stderr

p2p:
  listen_address: /ip4/0.0.0.0/tcp/3100
  public_address: /ip4/0.0.0.0/tcp/3100
  topics_of_interest:
    blocks: high
    messages: high
  trusted_peers: [
    /ip4/3.123.177.192/tcp/3000,
    /ip4/3.123.155.47/tcp/3000,
    /ip4/52.57.157.167/tcp/3000,
    /ip4/3.112.185.217/tcp/3000,
    /ip4/18.140.134.230/tcp/3000,
    /ip4/18.139.40.4/tcp/3000,
    /ip4/3.115.57.216/tcp/3000,
  ]
  
rest:
  listen: "127.0.0.1:3101"

storage: /tmp/jormungandr
```

**Comment by djculli** [comment]
perfect that worked thanks
