### ISSUE TITLE
could not connect with node when checking balance of receiver account

### ISSUE THREAD

**Issue by djculli** [input-output-hk/shelley-testnet#51]
PS C:\users\dj\desktop\jormungandr-v0.5.2-x86_64-pc-windows-gnu> .\jcli rest v0 account get $(cat receiver_account.txt)
-h  http://127.0.0.1:3101/api
failed to make a REST request
  |-> could not connect with node
  |-> http://127.0.0.1:3101/api/v0/account/ee290bd4d6595f3446a34ccf65c06d45cb4f5cf3eb74e5af48cd6d95b020858e: error trying to connect: No connection could be made because the target machine actively refused it. (os error 10061)
  |-> No connection could be made because the target machine actively refused it. (os error 10061)
PS C:\users\dj\desktop\jormungandr-v0.5.2-x86_64-pc-windows-gnu>

**Comment by rinor** [comment]
Has your node completed the sync? 
Do you have in your logs smth like `INFO Starting server on 127.0.0.1:3101, scope: global`?

**Comment by djculli** [comment]
Sep 27 14:55:21.570 INFO Starting jormungandr 0.5.2 (HEAD-e7a3efe7, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Sep 27 14:55:21.572 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Sep 27 14:55:21.573 INFO storing blockchain in '"/tmp/jormungandr\\blocks.sqlite"', task: init
Sep 27 14:55:27.506 INFO connecting to bootstrap peer 52.57.157.167:3000, peer_addr: 52.57.157.167:3000, task: bootstrap
Sep 27 14:55:27.872 ERRO with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 52.57.157.167:3000, task: bootstrapSep 27 14:55:27.874 INFO connecting to bootstrap peer 3.115.57.216:3000, peer_addr: 3.115.57.216:3000, task: bootstrap
Sep 27 14:55:28.138 ERRO with initial bootstrap, reason: bootstrap pull request failed, peer_addr: 3.115.57.216:3000, task: bootstrap
Sep 27 14:55:28.161 INFO connecting to bootstrap peer 3.123.155.47:3000, peer_addr: 3.123.155.47:3000, task: bootstrap
Sep 27 14:55:28.495 ERRO with initial bootstrap, reason: bootstrap pull request failed, peer_addr: 3.123.155.47:3000, task: bootstrap
Sep 27 14:55:28.498 INFO connecting to bootstrap peer 18.140.134.230:3000, peer_addr: 18.140.134.230:3000, task: bootstrap
Sep 27 14:55:28.915 ERRO with initial bootstrap, reason: bootstrap pull request failed, peer_addr: 18.140.134.230:3000, task: bootstrap
Sep 27 14:55:28.916 INFO connecting to bootstrap peer 3.123.177.192:3000, peer_addr: 3.123.177.192:3000, task: bootstrap
Sep 27 14:55:29.269 ERRO with initial bootstrap, reason: bootstrap pull request failed, peer_addr: 3.123.177.192:3000, task: bootstrap
Sep 27 14:55:29.273 INFO connecting to bootstrap peer 3.112.185.217:3000, peer_addr: 3.112.185.217:3000, task: bootstrap
Sep 27 14:55:29.542 ERRO with initial bootstrap, reason: bootstrap pull request failed, peer_addr: 3.112.185.217:3000, task: bootstrap
Sep 27 14:55:29.546 INFO connecting to bootstrap peer 18.139.40.4:3000, peer_addr: 18.139.40.4:3000, task: bootstrap
Sep 27 14:55:29.958 ERRO with initial bootstrap, reason: bootstrap pull request failed, peer_addr: 18.139.40.4:3000, task: bootstrap
Sep 27 14:55:29.964 INFO starting task, task: client-query
Sep 27 14:55:29.966 INFO starting task, task: network
Sep 27 14:55:29.968 INFO adding P2P Topology module: trusted-peers, task: network
Sep 27 14:55:29.970 INFO start listening and accepting gRPC connections on 0.0.0.0:3100, task: network
Sep 27 14:55:29.971 INFO Starting 1 workers, scope: global
Sep 27 14:55:29.972 INFO Starting server on 127.0.0.1:3101, scope: global
Sep 27 14:55:29.974 INFO connecting to initial gossip peer, peer_addr: 3.112.185.217:3000, task: network
Sep 27 14:55:29.977 INFO connecting to initial gossip peer, peer_addr: 3.115.57.216:3000, task: network
Sep 27 14:55:29.979 INFO connecting to initial gossip peer, peer_addr: 52.57.157.167:3000, task: network
Sep 27 14:55:29.981 INFO connecting to initial gossip peer, peer_addr: 18.139.40.4:3000, task: network
Sep 27 14:55:29.984 INFO connecting to initial gossip peer, peer_addr: 3.123.177.192:3000, task: network
Sep 27 14:55:29.988 INFO connecting to initial gossip peer, peer_addr: 3.123.155.47:3000, task: network
Sep 27 14:55:29.990 INFO connecting to initial gossip peer, peer_addr: 18.140.134.230:3000, task: network

**Comment by kishortungal** [comment]
I'm facing the same problem, when i try to check the balance i get 'Sep 27 23:06:45.046 WARN Error occurred during request handling: Account does not exist, scope: global' message.

Following the full message

failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3101/api/v0/account/a51f3589f8061ad13cc890734d906a3c26105d831356a1348884d21cec8a7837: Client Error: 404 Not Found

**Comment by kishortungal** [comment]
Please relaunch the node and try checking your balance

**Comment by ssainball** [comment]
![Screenshot from 2019-09-29 06-40-48](https://user-images.githubusercontent.com/35214356/65823804-0519e400-e298-11e9-83bb-33af93fac569.png)

I don't know what I should do.

**Comment by djculli** [comment]
PS C:\users\dj\desktop\jormungandr-v0.5.2-x86_64-pc-windows-gnu> .\jcli rest v0 account get $(cat receiver_account.txt)
-h  http://127.0.0.1:3101/api
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3101/api/v0/account/ee290bd4d6595f3446a34ccf65c06d45cb4f5cf3eb74e5af48cd6d95b020858e: Client Error: 404 Not Found
PS C:\users\dj\desktop\jormungandr-v0.5.2-x86_64-pc-windows-gnu>
