### ISSUE TITLE
Stuck at launching the node

### ISSUE THREAD

**Issue by embraceitandfaceit** [input-output-hk/shelley-testnet#58]
I will provide my log here:

![image](https://user-images.githubusercontent.com/55874818/65829064-ad807600-e2a1-11e9-81f9-e89a2188692e.png)

![image](https://user-images.githubusercontent.com/55874818/65829104-f33d3e80-e2a1-11e9-8146-79f9ee2e2713.png)

I pasted the configuration in the .yaml file like described. Is there anything I did wrong here?

**Comment by gmanroney** [comment]
I think the problem here is that you're trying to run an executable compiled for ARM on x86-64 architecture. What is the h/w you are using? What version of linux? You might want to try jormungandr-v0.5.2-x86_64-unknown-linux-gnu.tar.gz

**Comment by embraceitandfaceit** [comment]
![image](https://user-images.githubusercontent.com/55874818/65829233-698e7080-e2a3-11e9-8b71-dbd2385d9388.png)
Hi this is the version that is installed on my dedicated server. Should I install a second version of Ubuntu that is compatible with the stuff I have to perform here?

**Comment by embraceitandfaceit** [comment]
Got another issue now while using the testnet and setting up keys.

Now I'm getting jcli: command not found for some reason. It does create the files but for instance the receiver_account.txt is empty

![image](https://user-images.githubusercontent.com/55874818/65829949-1b7d6b00-e2ab-11e9-9382-30c2fdf2c755.png)

**Comment by rinor** [comment]
use ./jcli and ./jormungandr

**Comment by embraceitandfaceit** [comment]
Thank you buddy that solved it

**Comment by gmanroney** [comment]
@elviejo79 can you review user experience here and consider what changes we can make to our content and installation scripts to minimize or prevent reoccuence please?

**Comment by embraceitandfaceit** [comment]
Hi guys, I got another weird little thing. When I try to launch the node it on the last lign it says "connecting" instead of "fetching block". Any reason why it's refusing to fetch a block?

I appreciate the guidance guys.

![image](https://user-images.githubusercontent.com/55874818/65830616-51255280-e2b1-11e9-8c00-049a0e65fb06.png)

**Comment by rinor** [comment]
> Hi guys, I got another weird little thing. When I try to launch the node, on the last lign it says "connecting" instead of "fetching block". Any reason why it's refusing to fetch a block? I noticed the checking of the balance didn't work after successfully creating an address.
> 
> I appreciate the guidance guys.
> 
> ![image](https://user-images.githubusercontent.com/55874818/65830616-51255280-e2b1-11e9-8c00-049a0e65fb06.png)

It is normal since it if fetching the genesis block for the first time and storing it in your local storage.

**Comment by embraceitandfaceit** [comment]
ah right, more stuff is being added on the bottom :-) Nice!

How long should I wait before this is over? Or can I just continue to enter commands?
![image](https://user-images.githubusercontent.com/55874818/65830707-369fa900-e2b2-11e9-9143-a3283235cae6.png)

**Comment by rinor** [comment]
Now your node is ready.

**Comment by embraceitandfaceit** [comment]
Thank you for your help Rinor. With what key combination can I progress to checking the balance because I cannot type any command atm and I am afraid that ctrl+c will shut down the node or am I wrong?

![image](https://user-images.githubusercontent.com/55874818/65830750-a1e97b00-e2b2-11e9-8bc0-6d7b1d8d2411.png)

**Comment by rinor** [comment]
> Thank you for your help Rinor. With what key combination can I progress to checking the balance because I cannot type any command atm and I am afraid that ctrl+c will shut down the node or am I wrong?
> 
> ![image](https://user-images.githubusercontent.com/55874818/65830750-a1e97b00-e2b2-11e9-8bc0-6d7b1d8d2411.png)

Depends on your setup:
If you are connecting remotely on you node with a console (ssh or whatever is your setup), just open a new session/console, go to the same folder and start using ./jcli commands.

**Comment by embraceitandfaceit** [comment]
I just opened a new session in which the node is running.
Now I tried to check the balance from another session and I get another error unfortunately. Sorry bud :-D
![image](https://user-images.githubusercontent.com/55874818/65831009-ed048d80-e2b4-11e9-8631-b68bf3d031ac.png)

**Comment by dorin100** [comment]
Hi @embraceitandfaceit. After getting funds from Faucet, like on any other transaction, that transaction should be included into a block in order for the blockchain to know about your account.

Then, in order for your node to know about the transactions, it needs to receive blocks. You can take a look at this file (https://github.com/input-output-hk/shelley-testnet/wiki/How-do-I-know-that-my-node-is-in-%60sync%60) in order to understand if your node is receiving any blocks.

If there are any unclarities, please open a separate issue.  We will keep this open in order to track the linux documentation update.

**Comment by dorin100** [comment]
The linux documentation issue is a duplicate on this one: https://github.com/input-output-hk/shelley-testnet/issues/57

**Comment by jakewyo** [comment]
Hi @embraceitandfaceit you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by dorin100** [comment]
Hi @embraceitandfaceit . Is it ok if we close this issue as I see that you were able to start the node? 

We also improved the tutorials both for [Windows](https://iohk.zendesk.com/hc/en-us/articles/360036898153-How-to-install-Jormungandr-Networking-Linux-macOS-) and  [Linux/macOS](https://iohk.zendesk.com/hc/en-us/articles/360036898153-How-to-install-Jormungandr-Networking-Linux-macOS-)
