### ISSUE TITLE
Cannot send certificate to blockchain with instructions provided

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/shelley-testnet#59]
**Describe the bug**
Document to create stakepool does not work https://github.com/input-output-hk/shelley-testnet/wiki/How-to-create-a-Stake-Pool

> 6. Send the signed Stake Pool certificate to the blockchain
> bash faucet-send-certificate.sh stake_pool.signcert

Gives an error

> $ bash faucet-send-certificate.sh ../stake_pool.signcert  --account-spending-counter 1
> failed to make a REST request
>   |-> node rejected request because of invalid parameters
>   |-> http://127.0.0.1:8443/api/v0/account/xxxxxxxxxxxxxxxxxxx: Client Error: 404 Not Found
> error: Invalid value for '--account-spending-counter <account-spending-counter>': cannot parse integer from empty string
> 

**To Reproduce**
Follow steps 1 through 5 in https://github.com/input-output-hk/shelley-testnet/wiki/How-to-create-a-Stake-Pool

**Expected behavior**
Certificate should be sent to blockchain; is not because of error

**Additional context**
None

**Comment by dorin100** [comment]
Hi @gmanroney. I updated the step no 6 from the specified document. There is a separate file now that is taking you thru the manual steps you need to execute in order to send the transaction (certificate submission) to the blockchain. 

For advanced users, there are some scripts and new articles to follow.

**Comment by dorin100** [comment]
Hi @gmanroney . Once your node is `synced` (details [here](https://iohk.zendesk.com/hc/en-us/articles/360036404114) ), you can configure the Stake Pool either manually by following [this tutorial](https://iohk.zendesk.com/hc/en-us/articles/360036444094-How-to-send-a-Certificate-to-the-blockchain-manually) or using a script as explained in one of these tutorials - [for Windows](https://iohk.zendesk.com/hc/en-us/articles/360036958953-How-to-create-a-Stake-Pool-using-a-script-Windows-) or for [Linux/maxOS](https://iohk.zendesk.com/hc/en-us/articles/360036958993-How-to-create-a-Stake-Pool-using-a-script-Linux-macOS-). 

Make sure to use the latest version that is [0.5.6](https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6)

**Comment by carl-IOHK** [comment]
@gmanroney how did you do? Were you able to use the new documentation to make this work?

**Comment by carl-IOHK** [comment]
Since we didn't hear back from you we have closed this ticket as we assume the issue is resolved. Please use https://iohk.zendesk.com/hc/en-us/requests/new if you want to log any new issues we are not actively supporting this repo any more.
