### ISSUE TITLE
cannot read the node configuration file

### ISSUE THREAD

**Issue by djculli** [input-output-hk/shelley-testnet#60]
this is for a macbook

alys-mbp:jormungandr-v0.5.2-x86_64-apple-darwin alycullinane$ ./jormungandr --config ./node-config.yaml \--genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 \--log-level=info
Error in the overall configuration of the node
 |-> Cannot read the node configuration file: No such file or directory (os error 2)
 |-> No such file or directory (os error 2)

**Comment by metastrix** [comment]
Do you have this file stored in the executing directory?

` ./jormungandr --config ./node-config.yaml --genesis-block-hash`

you can define the path and filename through this commanc line paramter: **--config ./node-config.yaml**

**Comment by dorin100** [comment]
@carl-IOHK - can you help here?

**Comment by cliffc2** [comment]
check your echo $PATH
it is looking for the node-config.yaml in the wrong location.


for example
Doctors-MBP:~ cliff$ jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info
Error in the overall configuration of the node
 |-> Cannot read the node configuration file: No such file or directory (os error 2)
 |-> No such file or directory (os error 2)
Doctors-MBP:~ cliff$ cd jormungandr
Doctors-MBP:jormungandr cliff$ jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info
Oct 04 10:35:28.447 INFO Starting jormungandr 0.5.5 (HEAD-aec29a1c, release, macos [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Oct 04 10:35:28.448 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Oct 04 10:35:28.448 INFO storing blockchain in '"/tmp/jormungandr/blocks.sqlite"', task: init
 ^C

i use this osx command line. 
jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info

**Comment by jakewyo** [comment]
Hi @djculli you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6
