### ISSUE TITLE
eror with initial bootstrap: reason initial bootstrap stream failed

### ISSUE THREAD

**Issue by djculli** [input-output-hk/shelley-testnet#61]
PS C:\users\dj\desktop\jormungandr-v0.5.2-x86_64-pc-windows-gnu> .\jormungandr --config node-config.yaml --genesis-block
-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info
Sep 29 10:17:39.911 INFO Starting jormungandr 0.5.2 (HEAD-e7a3efe7, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Sep 29 10:17:39.913 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Sep 29 10:17:39.914 INFO storing blockchain in '"/tmp/jormungandr\\blocks.sqlite"', task: init
Sep 29 10:17:45.753 INFO connecting to bootstrap peer 18.140.134.230:3000, peer_addr: 18.140.134.230:3000, task: bootstrap
Sep 29 10:17:46.180 ERRO with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 18.140.134.230:3000, task: bootstrap
Sep 29 10:17:46.184 INFO connecting to bootstrap peer 3.112.185.217:3000, peer_addr: 3.112.185.217:3000, task: bootstrap
Sep 29 10:17:46.490 ERRO with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 3.112.185.217:3000, task: bootstrap
Sep 29 10:17:46.493 INFO connecting to bootstrap peer 52.57.157.167:3000, peer_addr: 52.57.157.167:3000, task: bootstrap
Sep 29 10:17:46.842 ERRO with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 52.57.157.167:3000, task: bootstrap
Sep 29 10:17:46.845 INFO connecting to bootstrap peer 3.123.155.47:3000, peer_addr: 3.123.155.47:3000, task: bootstrap
Sep 29 10:17:47.193 ERRO with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 3.123.155.47:3000, task: bootstrap
Sep 29 10:17:47.197 INFO connecting to bootstrap peer 3.123.177.192:3000, peer_addr: 3.123.177.192:3000, task: bootstrap
Sep 29 10:17:47.552 ERRO with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 3.123.177.192:3000, task: bootstrap
Sep 29 10:17:47.555 INFO connecting to bootstrap peer 3.115.57.216:3000, peer_addr: 3.115.57.216:3000, task: bootstrap
Sep 29 10:17:47.851 ERRO with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 3.115.57.216:3000, task: bootstrap
Sep 29 10:17:47.854 INFO connecting to bootstrap peer 18.139.40.4:3000, peer_addr: 18.139.40.4:3000, task: bootstrap
Sep 29 10:17:48.304 ERRO with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 18.139.40.4:3000, task: bootstrap
Sep 29 10:17:48.312 INFO starting task, task: client-query
Sep 29 10:17:48.315 INFO starting task, task: network
Sep 29 10:17:48.319 INFO adding P2P Topology module: trusted-peers, task: network
Sep 29 10:17:48.320 INFO start listening and accepting gRPC connections on 0.0.0.0:3100, task: network
Sep 29 10:17:48.322 INFO Starting 1 workers, scope: global
Sep 29 10:17:48.326 INFO Starting server on 127.0.0.1:3101, scope: global
Sep 29 10:17:48.329 INFO connecting to initial gossip peer, peer_addr: 3.112.185.217:3000, task: network
Sep 29 10:17:48.336 INFO connecting to initial gossip peer, peer_addr: 3.115.57.216:3000, task: network
Sep 29 10:17:48.340 INFO connecting to initial gossip peer, peer_addr: 52.57.157.167:3000, task: network
Sep 29 10:17:48.342 INFO connecting to initial gossip peer, peer_addr: 18.139.40.4:3000, task: network
Sep 29 10:17:48.353 INFO connecting to initial gossip peer, peer_addr: 3.123.177.192:3000, task: network
Sep 29 10:17:48.356 INFO connecting to initial gossip peer, peer_addr: 3.123.155.47:3000, task: network
Sep 29 10:17:48.362 INFO connecting to initial gossip peer, peer_addr: 18.140.134.230:3000, task: network

**Comment by metastrix** [comment]
your error is handled here: [input-output-hk/jormungandr/issues/843](https://github.com/input-output-hk/jormungandr/issues/843)

**Comment by dorin100** [comment]
Hi @djculli . The scope of the trusted peers is that one of them to provide the block0 to our local nodes. Sometimes some of the trusted peers might be down, but we need at least 1 up and working in order to have our node started. 

Can you please take a look at this file - https://github.com/input-output-hk/shelley-testnet/wiki/How-do-I-know-that-my-node-is-in-%60sync%60 - and let me know if your node is `sync` (receiving blocks)? 

There is already an issue that we are tracking for the trusted peers going down - https://github.com/input-output-hk/shelley-testnet/issues/65

**Comment by jakewyo** [comment]
Hi @djculli you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6
