### ISSUE TITLE
Node receiving blocks at startup, but nothing else happening. 'blockRecvCnt' remains at 0.

### ISSUE THREAD

**Issue by noneymous** [input-output-hk/shelley-testnet#62]
**Describe the bug**
I tried to run a networking node, according to the guide at https://github.com/input-output-hk/shelley-testnet/wiki/How-to-setup-a-Jormungandr-Networking--node-%28v-0.5.0%29 on a standard Ubuntu Linux. The node starts fine and loads its first blocks, but then it idles and does not receive new blocks [from its peers]. If I restart the node I see a higher block height, but nothing more is happening.

**To Reproduce**
1. Deployed as described in https://github.com/input-output-hk/shelley-testnet/wiki/How-to-setup-a-Jormungandr-Networking--node-%28v-0.5.0%29
2. Updated "public_address:" in the yaml config to the public IP my host is reachable at
3. Verified that I can actually connect to that IP via the internet (works fine)
3. Started node: ./jormungandr --config ./node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=debug
4. Waited some time
5. Checked node status:  jcli rest v0 node stats get --host http://localhost:3101/api
4. Stats, except uptime, not changing:

```
ubuntu:~/jormungandr$ jcli rest v0 node stats get --host http://localhost:3101/api
---
blockRecvCnt: 0
lastBlockDate: "219.17968"
lastBlockFees: 0
lastBlockHash: bc2dd88c49bb543967df5bfb0dbea7838af31bcd824bdc55482227f37e403967
lastBlockHeight: "23833"
lastBlockSum: 0
lastBlockTime: ~
lastBlockTx: 0
txRecvCnt: 0
uptime: 2
```

**Expected behavior**
I expected to see block receive count and height increasing over time.

**Additional context**
After restarting jormungandr, I see a heigher block height, but it's still not receiving new blocks:

```
ubuntu:~/jormungandr$ jcli rest v0 node stats get --host http://localhost:3101/api
---
blockRecvCnt: 0
lastBlockDate: "219.18021"
lastBlockFees: 0
lastBlockHash: 75d927599549db6bc66c8a80eed71b9762b4768373eb6e6a02a9b04fa3754ca4
lastBlockHeight: "23846"
lastBlockSum: 0
lastBlockTime: ~
lastBlockTx: 0
txRecvCnt: 0
uptime: 6
```

**Comment by noneymous** [comment]
Is there no Cardano Discord or some other interactive technical community channel to discuss and get support? Creating a Github issue for this feels a bit extreme...

**Comment by metastrix** [comment]
look into the discussion here: [input-output-hk/jormungandr/issues/860](https://github.com/input-output-hk/jormungandr/issues/860)

try this config.yaml

```
storage: "<your bc storage>"

p2p:
  public_address: "/ip4/79.143.188.85/tcp/3000"
  trusted_peers: [/ip4/3.123.177.192/tcp/3000,
                  /ip4/3.123.155.47/tcp/3000,
                  /ip4/52.57.157.167/tcp/3000,
                  /ip4/3.112.185.217/tcp/3000,
                  /ip4/18.140.134.230/tcp/3000,
                  /ip4/18.139.40.4/tcp/3000,
                  /ip4/3.115.57.216/tcp/3000]
  topics_of_interest:
    messages: high
    blocks: high

rest:
  listen: "127.0.0.1:8443"
```

**Comment by noneymous** [comment]
Thank's for the link. Unfortunately, it did not work, I tried different config formats and ports.

I'm closing this, as the other one seems to be a similar issue.
