### ISSUE TITLE
Can't send stake_pool.signcert to blockchain via faucet-send-certificate.sh

### ISSUE THREAD

**Issue by JScryptobounty** [input-output-hk/shelley-testnet#64]
**Describe the bug**
I have a fully working node and when following the documentation to create a Stake Pool so I can delegate, I get an Invalid Length error, 

specifically:
 "invalid Bech32
  |-> invalid length"

**To Reproduce**
1. Create a working jormungandr testnet node
2. Follow https://github.com/input-output-hk/shelley-testnet/wiki/How-to-create-a-Stake-Pool instructions
3. Modify the faucet-send-certificate.sh script with the following: 
### TEMPLATE
FAUCET_SK=
BLOCK0_HASH="adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770"
REST_URL="http://127.0.0.1:3101/api"
CLI=`which jcli`
COLORS=0
FEE_CONSTANT=1000
FEE_CERTIFICATE=10000
FEE_COEFFICIENT=50
ADDRTYPE="--testing"

5. run" bash faucet-send-certificate.sh stake_pool.signcert" 
Get error "Invalid Bech32 |-> invalid length"

**Expected behavior**
Expect pool to appear in available stake pools on the blockchain.

**Comment by lednersin** [comment]
It looks like the stake_pool.signcert is not valid.
The
jcli certificate sign receiver_secret.key stake_pool.cert stake_pool.signcert
command simply outputs the stake_pool.cert.
Probably the last line in jcli_app/certificate/sign.rs should be:
write_cert(self.output, CertificateType(cert))

**Comment by dorin100** [comment]
@JScryptobounty - I just updated the [How to create a Stake Pool](https://github.com/input-output-hk/shelley-testnet/wiki/How-to-create-a-Stake-Pool) file. Please execute the manual steps to send the Certificate to the blockchain.

The scripts are only an example of the operations that need to be done and are intended for advanced users that understand what they need to change in order to have them working. 

Please let me know if you have any issues.

**Comment by jakewyo** [comment]
Hi @JScryptobounty you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by dorin100** [comment]
Hi @JScryptobounty - we updated the tutorials related to Stake Pool creation. You can execute the steps manually (https://iohk.zendesk.com/hc/en-us/articles/360036969013-How-to-create-a-Stake-Pool-manually) or you can use a script - on windows (https://iohk.zendesk.com/hc/en-us/articles/360036958953-How-to-create-a-Stake-Pool-using-a-script-Windows-) or on linux/macOS (https://iohk.zendesk.com/hc/en-us/articles/360036958993-How-to-create-a-Stake-Pool-using-a-script-Linux-macOS-)

Please let us know how it works.

**Comment by dorin100** [comment]
Documentation was updated so this should not be an issue anymore. Please open a new issue if there will be the case. Thank you!
