### ISSUE TITLE
Use of the term self node is confusing

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#66]
**Describe the bug**
On the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/

Issue 1. SETTING UP THE SELF NODE
Use of the term self node is confusing since that is an isolated node. Suggest changing this. 

**To Reproduce**
1. got to https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
See SETTING UP THE SELF NODE page title. 

**Expected behavior**
1. signpost what is for self node and what is for networked testnet clearly
2. if instructions are valid for both, then mention that. 

**Additional context**
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet

**Comment by dorin100** [comment]
duplicate of https://github.com/input-output-hk/shelley-testnet/issues/72

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
