### ISSUE TITLE
Change order of Install instructions and signpost them for non-technical users

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#67]
**Describe the bug**
Issue 2. How to install Jörmungandr from source:
Suggest we signpost that is is for developers and change the order that these are listed in to put the easy one  (How to install Jörmungandr from a release:) on top. And also say that  How to install Jörmungandr from a release is appropriate for CP

On the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/

**To Reproduce**
1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. See How to install Jörmungandr from source:

**Expected behavior**

**Additional context**
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by cliffc2** [comment]
I've been taking some notes of the steps and logic.

https://github.com/cliffc2/cliffnotes

a pdf file is here. 
[testnet osx terminal 3.pdf](https://github.com/input-output-hk/shelley-testnet/files/3686242/testnet.osx.terminal.3.pdf)

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
