### ISSUE TITLE
Signpost the release files clearly

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#68]
**Describe the bug**
Issue 3.
2. Choose the file that matches your hardware and operating system.
On https://github.com/input-output-hk/jormungandr/releases it is not obvious to CP which file to use so it would help to signpost the release files clearly 
E.g. Windows has 3 different versions and the one that says apple is apparently not for macOS (Dorin advised me to use jormungandr-v0.5.0-x86_64-unknown-linux-gnu.tar on macOS but if not for Dorin I would not have known what to use). 

**To Reproduce**
1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. Find section 2. Choose the file that matches your hardware and operating system.
3. Follow the link to the release files. 

**Expected behavior**
signpost the release files clearly

**Additional context**
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
