### ISSUE TITLE
Improve documentation on updating system PATH variables

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#69]
**Describe the bug**
Issue 4. 
5. Add the executables to the PATH of your system.
We need to help CP to change their path, they will not know how to do this. 
Also it is not clear if this is Windows or macOS related. The instructions need to be added for both OS. 

**To Reproduce**

1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. 5. Add the executables to the PATH of your system.
**Expected behavior**
Instructions exist to guide CP to change their PATH, for Windows or macOS 

**Additional context**
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
