### ISSUE TITLE
Need clear step-by-step quick-start guide for staking testnet

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/shelley-testnet#7]
For the Shelley staking testnet we need:

* The README and/or quickstart section of the user guide needs to provide step by step instructions to get a standalone node (or nodes) up and running.
* This must include at least one example config that works in the single machine context.
* This must include at least one example genesis block yaml, and step by step commands to turn it into a binary format needed to run a node.

The step by step instructions need to be tested to make sure they work literally as-is without any missing steps. We should not make users guess or go searching through the rest of the docs.

I suggest structuring the introduction this way so that people can get a basic thing working without having to think too hard, and then as a follow-up once they have achieved the basic starting point then it's the moment for the docs to describe more concepts and how to cusomise things, and set up stake pools etc. So start with a sense of achievement and confirmation for getting the basics working, then describe the more advanced things.

Bonus user guide / quick start doc tips:

* Don't leave critical info to the end, e.g. per-OS info, include it at the moment it is relevant. Imagine people are literally following the instructions in order, not reading everything through first.
* Don't suggest people consider trying something. Tell them what to do exactly.
* Be careful with examples. People will copy and paste them. Don't leave templates that need details to be filled in if you can help it. Provide examples that simply work, or if that's not possible be super explicit about what needs to be filled in.

**Comment by elviejo79** [comment]
Hi @dcoutts !  How are you ?  We built the documentation trying to follow your guide lines and requests: 

- We have this How-to guide:  https://github.com/input-output-hk/shelley-testnet/wiki 
- And this series of video tutorials:  https://www.youtube.com/playlist?list=PLnPTB0CuBOBzHmIMplX6BT6F3tzKOSFG5

Do you think this covers your suggestions?

**Comment by dorin100** [comment]
There are clear steps and scripts for starting the node now.
