### ISSUE TITLE
Complete set of scripts exists for each OS

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#70]
**Describe the bug**
Issue 5. 
6. Go to the Scripts folder in the GitHub repository.
The files in this location are not identified by OS. Although we think they are OS specific. It would be great to have this broken down into subdirectories for Windows Mac and Linux with the scripts for each OS listed in the subdirectory. Like e.g.  jormungandr/scripts/Windows

Issue 6. We are apparently missing scripts for many operations for some OS. Apparently, only bootstrap.ps1 is for =windows and the rest are for Linux, not sure if Linux incldes macOS or not. 

**To Reproduce**

Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. find 6. Go to the Scripts folder in the GitHub repository.
3. Follow the link to Scripts

**Expected behavior**
Scripts broken down into subdirectories for Windows Mac and Linux with the scripts for each OS listed in the subdirectory. Like e.g.  jormungandr/scripts/Windows. 
Complete set of scripts exists for each OS in each subdirectory. 

**Additional context**
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
