### ISSUE TITLE
Let non-technical users know that .sh is a file extension; and explain how to give it executable permissions

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#71]
**Describe the bug**
Issue 7. 
9. Save it as a script (.sh) and give it executable permissions.
It would be good to let CP know that .sh is a file extension. Also explain how to give it executable permissions. We don't know what give it executable permissions means and if this process differs by OS (I guess it does). 

**To Reproduce**

1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. find 9. Save it as a script (.sh) and give it executable permissions

**Expected behavior**
let CP know that .sh is a file extension. Also explain how to give it executable permissions; and ensure that those instructions are available for all 3 supported OS. 

**Additional context**
Please add any other context about the problem here.

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
