### ISSUE TITLE
Rewrite How to install Jörmungandr from source: steps 6-10 so that non-tech users can follow them. 

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#72]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**

1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. Find 10. Perform steps 7 to 9 for:
  create-account-and-delegate.shtempl
  faucet-send-certificate.shtempl
  faucet-send-money.shtempl
  send-transaction
3. go the the scripts folder link in step 6 

**Expected behavior**
Rewrite steps 6-10 so that CP can follow them. 

**Additional context**
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by dorin100** [comment]
If you click on `Get Started` all the details from there are for `SETTING UP THE SELF NODE` and not the node connected to a network.

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
