### ISSUE TITLE
Clarify Jcli-helpers instructions

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#74]
**Describe the bug**
Issue 9. 
11. In Jcli-helpers,
execute the
bootstrap.sh
file.
We just do not understand what we should do here, I've never heard of executing one file inside of another file... 

**To Reproduce**

1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. Find: 11. In Jcli-helpers,

**Expected behavior**
A clear and concise description of what the user is expected to do with Jcli-helpers,.

**Additional context**
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
