### ISSUE TITLE
Expectations of what we want non-technical users to do with this testnet are not documented

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#76]
**Describe the bug**
Issue 11. 
Expectations of what we want CP to do with this testnet are not communicated or documented. 

**To Reproduce**
1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2., Read the content and see if it would make sense to a non-technical user.
3. Consider if this testnet is appropriate for non-technical users. 

**Expected behavior**
We should list what the goals of the documentation are. Maybe we should post the CP instructions in the IOHK Support Portal. The goals and target audience could also be discussed here: https://testnet.iohkdev.io/cardano/shelley/about/infrastructure/ along with system requirements and supported OS versions and minimum machine specs. 

**Additional context**
Please add any other context about the problem here.
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
