### ISSUE TITLE
A clear and non-technical description of what you can expect to happen when using this networked testnet is missing. 

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#78]
**Describe the bug**
Issue 13. 
**The self node configuration includes a Yaml file (loaded to the bootstrap script) that allows you to build your own blockchain and set its parameters. It bootstraps your own genesis block and enables your machine to run a multi-node environment. Here you can experiment with your own version of Ouroboros Genesis, manually build transactions, and demonstrate the workings of the cryptocurrency.**

This explanation is great but for CP it's very dense and hard to understand. So if we want CP to be enlighted we should expand this and make it easier for CP to consume the information. 

**To Reproduce**
1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. Find the text The self node configuration includes a Yaml file...

**Expected behavior**
A clear and concise description of what you can expect to happen when using this networked testnet. 

**Additional context**
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
