### ISSUE TITLE
Ouroboros Genesis is mentioned but in the handover, Ouroboros Praos was identified as the POS protocol

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#79]
**Describe the bug**
Issue 14. in the text in Issue 13 Ouroboros Genesis is mentioned but in the handover, Ouroboros Praos was identified as the POS protocol. 

**To Reproduce**
Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. find Ouroboros Genesis

**Expected behavior**
Replace Ouroboros Genesis with Ouroboros Praos

**Additional context**
Please add any other context about the problem here.

**Comment by vincenthz** [comment]
Sadly the confusing state is linked to the somewhat confusing choice in the papers; both are correct, and the most precise expected value is "ouroboros genesis praos".

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
