### ISSUE TITLE
Jormungandr comand instructions could be clarified for a non technical user. 

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#80]
**Describe the bug**
Issue 15. 12. To start the node, execute the following command:
jormungandr --genesis-block block-0.bin --config
config.yaml --secret poolsecret1.yaml`
Is genesis-block a variable for something that was set up by the scripts? If so are the scripts updated with the latest Genesi Block Hash? 

jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info
Maybe the user is suppoed to know that they should replace genesis-block with genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770  ? 

**To Reproduce**
1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. find the text 12. To start the node, execute the following command

**Expected behavior**
A clear and concise description of what to do with the .jormungandr --genesis-block block-0.bin --config
config.yaml --secret poolsecret1.yaml` comand and how it works. 

**Additional context**
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by dorin100** [comment]
You should not use `--genesis-block block-0.bin` to start the node.

Instead, you need to use `--genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770`

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
