### ISSUE TITLE
Navigation menu in testnet website not configured correctly 

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#81]
**Describe the bug**
Issue 16. Pages labelled SETTING UP THE SELF NODE and  SETTING UP ADDRESSES are not listed in the left navigation pane. You can only navigate to them when you start at GET STARTED. Also, the order of the pages using the Next --> navigation does not follow the order of the left navigation pane. As a CP user, I would expect to have a page named GET STARTED open if I click on GET STARTED and see the SETTING UP THE SELF NODE page in the left navigation panel... By the way, I would expect to see GETTING STARTED...

**To Reproduce**
1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. Use the next buttons to navigate from page to page
3. Compare this to the menu on the left. 

**Expected behavior**
Page headers should appear in the navigation menu of the site and also appear in the same order as the content is logically structured

**Additional context**
Please add any other context about the problem here.
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
