### ISSUE TITLE
Cannot run node

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#82]
**Describe the bug**

**To Reproduce**
1. Downloaded 0.5.4 

2. created node-config.yaml using text mate
log:
  format: "plain"
  level: "info"
  output: "stderr"
p2p:
  listen_address: "/ip4/94.46.167.18/tcp/3100"
  public_address: "/ip4/192.168.0.13/tcp/3100"
  topics_of_interest:
    blocks: "high"
    messages: "high"
  trusted_peers:
    - "/ip4/3.123.177.192/tcp/3000"
    - "/ip4/3.123.155.47/tcp/3000"
    - "/ip4/52.57.157.167/tcp/3000"
    - "/ip4/3.112.185.217/tcp/3000"
    - "/ip4/18.140.134.230/tcp/3000"
    - "/ip4/18.139.40.4/tcp/3000"
    - "/ip4/3.115.57.216/tcp/3000"
rest:
  listen: "127.0.0.1:3101"
storage: "/tmp/jormungandr"

3. and placed it in the folder with the executables

4. I updated ~/.bash_profile to contain
export IM_STUDIO_PATH="$HOME/Users/carlshepherd/Downloads/jormungandr-v0.5.4-aarch64-unknown-linux-gnu:$PATH"

5. when I run
./jormungandr --config ./node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info

6. I get this error

Carls-MacBook-Pro:jormungandr-v0.5.2-aarch64-unknown-linux-gnu carlshepherd$ ./jormungandr --config ./node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info
-bash: ./jormungandr: cannot execute binary file

**Expected behavior**
The node shouuld start

**Additional context**
I got a lot of help from Dorian but we could not figure it out together.

**Comment by jakewyo** [comment]
Documentation updated - closing

**Comment by jakewyo** [comment]
@dorin100 this can be closed per our discussion on Slack.

Thanks!
