### ISSUE TITLE
jcli: command not found

### ISSUE THREAD

**Issue by przemekdobosz** [input-output-hk/shelley-testnet#86]
Hi 
I'm on Debian 9
Following instruction can start jormungandr - newest version 5.5
However next steps can't be done because of jcli error
Full info in attachement
p
![jcli_error](https://user-images.githubusercontent.com/38405895/66047961-ff86fd00-e528-11e9-8d3d-80863ab5745d.JPG)

**Comment by dorin100** [comment]
Hi @przemekdobosz . What instructions are you following?

First, you need to start the node - https://github.com/input-output-hk/shelley-testnet/wiki/How-to-setup-a-Jormungandr-Networking--node-(--v0.5.0)

**Comment by elviejo79** [comment]
Have you tried `./jcli` ?

**Comment by przemekdobosz** [comment]
./jcli solved issue 
Thx

**Comment by PacificGreen** [comment]
So then this does beg the question as to why all the examples and documentation are referencing using just jcli instead of ./jcli ?

Is this not a security issue placing the ./ in the path variable as somebody could come along and replace the actual jcli file with their own?  I have had to change every reference to jcli in every single example given and in every script I have tried.  This is quite tedious.

**Comment by Philluminati** [comment]
i encoutered the same "problem". i think it should be updated in the doku. So that you have to start it with ./jcli in linux.

**Comment by jclarkv** [comment]
Good explanation here:
[http://www.linfo.org/dot_slash.html](http://www.linfo.org/dot_slash.html)

The good folks who wrote the docs almost certainly had the directory they were working in added to their PATH

**Comment by PacificGreen** [comment]
I imagine there are two sides to it.  I was always the type of system admin that preferred to put the dot slash manually in front of everything as I was already in the directory any for the most part.  Otherwise this is all I was referring to the example at the end of the page you referenced.

**Comment by jakewyo** [comment]
Hi @przemekdobosz you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by dorin100** [comment]
Hi @przemekdobosz . We improved the documentation and moved it here - https://iohk.zendesk.com/hc/en-us/articles/360036898153-How-to-install-Jormungandr-Networking-Linux-macOS-

Can we close this issue? Is there anything that still needs to be clarified related to this issue?

**Comment by przemekdobosz** [comment]
Sure
  
  
   Thanks, please close it
  
  
   p
  
  
   Dnia 9 października 2019 o 10:22 Dorin Solomon <notifications@github.com> napisał(a): 
    
   
   Hi @przemekdobosz . We improved the documentation and moved it here - https://iohk.zendesk.com/hc/en-us/articles/360036898153-How-to-install-Jormungandr-Networking-Linux-macOS-
   Can we close this issue? Is there anything that still needs to be clarified related to this issue?

**Comment by dorin100** [comment]
Thank you!
