### ISSUE TITLE
Slow Faucet

### ISSUE THREAD

**Issue by ghost** [input-output-hk/shelley-testnet#89]
**Describe the bug
The testnet faucet is slow to release tokens resulting in this vague response:
TIMEOUT ERROR:
You have previously submitted a request and have exceeded the limit.

Please wait for a short interval before submitting another request.

** Prerequisites information

1. What is your Operating system?
Windows 10
1. What version of the jormungandr node are you using?
$ ./jormungandr -V
jormungandr 0.5.5
1. Did you use jormungandr installer (snap, chocolatey, brew, etc.)?
Downloaded from GitHub Manually the binary.

**To Reproduce
1. Delete account that was possibly not configured properly with no hope of recovering.
2. Create new account with script or by hand via directions for network node.
3. Go to Faucet ask for tokens again - denied.  So frusterating when one simply wants to work through the examples and get delegated.

**Expected behavior
Tokens please.  
**Additional context
Perhaps going back to the Byron with the captcha might work.  I did not feel like doing the wasm project for my own faucet.

**Comment by jakewyo** [comment]
You may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by dorin100** [comment]
The user was deleted. Closed as required by @Carl.
