### ISSUE TITLE
Adding storage line to node.config.yaml

### ISSUE THREAD

**Issue by ghost** [input-output-hk/shelley-testnet#93]
**Describe the bug
When I add the storage line into the node.config.yaml I see this in the logs:

Oct 04 13:49:38.471 INFO storing blockchain in jormungandrtmp (Double backslash) blocks.sqlite, task: init

It should be explicitly stated in that you must have a trailing backslash for it to render the path properly. 

** Prerequisites information

1. What is your Operating system?
Win 10
1. What version of the jormungandr node are you using?
5.5
1. Did you use jormungandr installer (snap, chocolatey, brew, etc.)?
Binary
**To Reproduce
1. Go to node.config.yaml
2. Use storage: "/tmp/jormungandr" on windows
3. Start the node and observe the malformed path.

**Comment by dorin100** [comment]
Closing this as the user was deleted from github... Not sure about the request too.
