### ISSUE TITLE
P2P connection error: Protocol Error: 104, ConnectionReset, peer_addr: 168.63.129.16

### ISSUE THREAD

**Issue by sedwardstx** [input-output-hk/shelley-testnet#95]
This is an informational bug report, feel free to close it immediately.

When running a networked node on Azure you may see this warning.  

Oct 05 14:58:21.175 WARN incoming P2P connection error: Protocol(Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })), peer_addr: 168.63.129.16:63078, task: network

**This is not a bug**, this is the Azure LoadBalancer sending health probes to the listener port your configured in the LB.  Since the probe request do not conform to the protocol, they are reset, this is the expected behavior.  

For more info on this well known IP (168.63.129.16) see https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-custom-probe-overview

**To Reproduce

somenode01:~$ ./jormungandr --config ./node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
Oct 05 14:57:03.128 INFO Starting jormungandr 0.5.5 (HEAD-aec29a1, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Oct 05 14:57:03.128 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Oct 05 14:57:03.128 INFO storing blockchain in '"/tmp/jormungandr/blocks.sqlite"', task: init
Oct 05 14:57:43.345 INFO connecting to bootstrap peer 3.123.155.47:3000, peer_addr: 3.123.155.47:3000, task: bootstrap
Oct 05 14:57:43.610 INFO initial bootstrap completed, peer_addr: 3.123.155.47:3000, task: bootstrap
Oct 05 14:57:43.612 INFO starting task, task: client-query
Oct 05 14:57:43.612 INFO starting task, task: network
Oct 05 14:57:43.613 INFO adding P2P Topology module: trusted-peers, task: network
Oct 05 14:57:43.613 INFO start listening and accepting gRPC connections on 0.0.0.0:3100, task: network
Oct 05 14:57:43.614 INFO Starting 1 workers, scope: global
Oct 05 14:57:43.614 INFO Starting server on 127.0.0.1:3101, scope: global
Oct 05 14:57:43.615 INFO connecting to initial gossip peer, peer_addr: 3.112.185.217:3000, task: network
Oct 05 14:57:43.615 INFO connecting to initial gossip peer, peer_addr: 3.115.57.216:3000, task: network
Oct 05 14:57:43.616 INFO connecting to initial gossip peer, peer_addr: 52.57.157.167:3000, task: network
Oct 05 14:57:43.617 INFO connecting to initial gossip peer, peer_addr: 18.139.40.4:3000, task: network
Oct 05 14:57:43.618 INFO connecting to initial gossip peer, peer_addr: 3.123.177.192:3000, task: network
Oct 05 14:57:43.618 INFO connecting to initial gossip peer, peer_addr: 3.123.155.47:3000, task: network
Oct 05 14:57:43.619 INFO connecting to initial gossip peer, peer_addr: 18.140.134.230:3000, task: network
Oct 05 14:57:46.110 INFO incoming P2P connection on 10.0.1.5:3100, peer_addr: 168.63.129.16:62787, task: network
Oct 05 14:57:51.125 WARN incoming P2P connection error: Protocol(Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })), peer_addr: 168.63.129.16:62787, task: network
Oct 05 14:57:51.126 INFO incoming P2P connection on 10.0.1.5:3100, peer_addr: 168.63.129.16:62825, task: network
Oct 05 14:57:56.141 WARN incoming P2P connection error: Protocol(Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })), peer_addr: 168.63.129.16:62825, task: network
Oct 05 14:57:56.142 INFO incoming P2P connection on 10.0.1.5:3100, peer_addr: 168.63.129.16:62865, task: network
Oct 05 14:58:01.141 WARN incoming P2P connection error: Protocol(Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })), peer_addr: 168.63.129.16:62865, task: network
Oct 05 14:58:01.142 INFO incoming P2P connection on 10.0.1.5:3100, peer_addr: 168.63.129.16:62902, task: network
Oct 05 14:58:06.157 WARN incoming P2P connection error: Protocol(Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })), peer_addr: 168.63.129.16:62902, task: network
Oct 05 14:58:06.157 INFO incoming P2P connection on 10.0.1.5:3100, peer_addr: 168.63.129.16:62970, task: network
Oct 05 14:58:11.172 WARN incoming P2P connection error: Protocol(Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })), peer_addr: 168.63.129.16:62970, task: network
Oct 05 14:58:11.174 INFO incoming P2P connection on 10.0.1.5:3100, peer_addr: 168.63.129.16:63024, task: network
Oct 05 14:58:16.172 WARN incoming P2P connection error: Protocol(Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })), peer_addr: 168.63.129.16:63024, task: network
Oct 05 14:58:16.173 INFO incoming P2P connection on 10.0.1.5:3100, peer_addr: 168.63.129.16:63078, task: network
Oct 05 14:58:21.175 WARN incoming P2P connection error: Protocol(Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })), peer_addr: 168.63.129.16:63078, task: network
Oct 05 14:58:21.175 INFO incoming P2P connection on 10.0.1.5:3100, peer_addr: 168.63.129.16:63127, task: network

**Comment by dorin100** [comment]
Thank you @sedwardstx !
