### ISSUE TITLE
Error in the overall configuration of the node

### ISSUE THREAD

**Issue by SViksha** [input-output-hk/shelley-testnet#96]
Followed the instruction on https://github.com/input-output-hk/shelley-testnet/wiki/How-to-setup-a-Jormungandr-Networking--node-(--v0.5.0)
 while running the node at last step giving me an following Error
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: while parsing a block mapping, did not find expected key at line 3 column 18
 |-> while parsing a block mapping, did not find expected key at line 3 column 18

**Comment by jclarkv** [comment]
Could you post your node-config file? That's what it seems to be referencing.

**Comment by SViksha** [comment]
log:
format: "plain"
level: "info"
output: "stderr"
p2p:
listen_address: "/ip4/0.0.0.0/tcp/3100"
public_address:
topics_of_interest:
blocks: "high"
messages: "high"
trusted_peers:
- "/ip4/3.123.177.192/tcp/3000"
- "/ip4/3.123.155.47/tcp/3000"
- "/ip4/52.57.157.167/tcp/3000"
- "/ip4/3.112.185.217/tcp/3000"
- "/ip4/18.140.134.230/tcp/3000"
- "/ip4/18.139.40.4/tcp/3000"
- "/ip4/3.115.57.216/tcp/3000"
rest:
listen: "127.0.0.1:3101"
storage: "/tmp/jormungandr"

**Comment by SViksha** [comment]
> Could you post your node-config file? That's what it seems to be referencing.

log:
  format: "plain"
  level: "info"
  output: "stderr"
p2p:
  listen_address: "/ip4/0.0.0.0/tcp/3100"
  public_address:
  topics_of_interest:
    blocks: "high"
    messages: "high"
  trusted_peers:
    - "/ip4/3.123.177.192/tcp/3000"
    - "/ip4/3.123.155.47/tcp/3000"
    - "/ip4/52.57.157.167/tcp/3000"
    - "/ip4/3.112.185.217/tcp/3000"
    - "/ip4/18.140.134.230/tcp/3000"
    - "/ip4/18.139.40.4/tcp/3000"
    - "/ip4/3.115.57.216/tcp/3000"
rest:
  listen: "127.0.0.1:3101"
storage: "/tmp/jormungandr"

**Comment by SViksha** [comment]
> Could you post your node-config file? That's what it seems to be referencing.

log:
  format: "plain"
  level: "info"
  output: "stderr"
p2p:
  listen_address: "/ip4/0.0.0.0/tcp/3100"
  public_address:
  topics_of_interest:
    blocks: "high"
    messages: "high"
  trusted_peers:
    - "/ip4/3.123.177.192/tcp/3000"
    - "/ip4/3.123.155.47/tcp/3000"
    - "/ip4/52.57.157.167/tcp/3000"
    - "/ip4/3.112.185.217/tcp/3000"
    - "/ip4/18.140.134.230/tcp/3000"
    - "/ip4/18.139.40.4/tcp/3000"
    - "/ip4/3.115.57.216/tcp/3000"
rest:
  listen: "127.0.0.1:3101"
storage: "/tmp/jormungandr"

**Comment by SViksha** [comment]
> > Could you post your node-config file? That's what it seems to be referencing.
> 
> log:
> format: "plain"
> level: "info"
> output: "stderr"
> p2p:
> listen_address: "/ip4/0.0.0.0/tcp/3100"
> public_address:
> topics_of_interest:
> blocks: "high"
> messages: "high"
> trusted_peers:
> - "/ip4/3.123.177.192/tcp/3000"
> - "/ip4/3.123.155.47/tcp/3000"
> - "/ip4/52.57.157.167/tcp/3000"
> - "/ip4/3.112.185.217/tcp/3000"
> - "/ip4/18.140.134.230/tcp/3000"
> - "/ip4/18.139.40.4/tcp/3000"
> - "/ip4/3.115.57.216/tcp/3000"
> rest:
> listen: "127.0.0.1:3101"
> storage: "/tmp/jormungandr"

Now it is giving me different error
root@vultr:~/Cardano# ./jormungandr --config ./node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
Error in the overall configuration of the node
 |-> Error while parsing the node configuration file: unknown field `format`, expected one of `secret_files`, `storage`, `log`, `mempool`, `leadership`, `rest`, `p2p`, `explorer` at line 2 column 1
 |-> unknown field `format`, expected one of `secret_files`, `storage`, `log`, `mempool`, `leadership`, `rest`, `p2p`, `explorer` at line 2 column 1
