### ISSUE TITLE
Could not connect with node v0.5.5

### ISSUE THREAD

**Issue by PierreLz** [input-output-hk/shelley-testnet#97]
**Describe the bug
I did succeed to run the node and make a transaction few days ago with the v0.5.2 but I can't connect anymore with v0.5.5.

** Prerequisites information

1. What is your Operating system? Ubuntu 16.04LTS
1. What version of the jormungandr node are you using? v0.5.5 
1. Did you use jormungandr installer (snap, chocolatey, brew, etc.)? Via cargo

**To Reproduce
Downloaded  jormungandr and did everything explicated
Start the node with ./jormungandr --config ./node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770

**Expected behavior
Should connect with the node

**Additional context
I get this logs and nothing more.

Oct 06 02:27:47.903 INFO Starting jormungandr 0.5.5 (HEAD-aec29a1, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Oct 06 02:27:47.904 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Oct 06 02:27:47.904 INFO storing blockchain in '"/tmp/jormungandr/blocks.sqlite"', task: init
Oct 06 02:27:47.911 INFO connecting to bootstrap peer 3.123.177.192:3000, peer_addr: 3.123.177.192:3000, task: bootstrap

Check:
➜  jormungandr-v0.5.5-x86_64-unknown-linux-gnu ./jcli rest v0 node stats get --host "http://127.0.0.1:3101/api"
failed to make a REST request
  |-> could not connect with node
  |-> http://127.0.0.1:3101/api/v0/node/stats: error trying to connect: Connection refused (os error 111)
  |-> Connection refused (os error 111)

Thank you

**Comment by jclarkv** [comment]
How long did you wait? I need to let it run for at least 15-20".  I eventually see the line:
`Oct 05 22:22:38.078 INFO Starting server on 127.0.0.1:8443, scope: global`
--in this case 2" after node start)

**Comment by Dmindfuse** [comment]
@PierreLz I agree with @jclarkv , you need to wait a certain amount of time for the REST calls to be able to connect. Though, I also reckon this requires better visibility to the end user (if it is a legitimate issue).

**Comment by PierreLz** [comment]
@jclarkv @Dmindfuse  I restarted the node and after 30 minutes I have this:

Oct 06 11:26:03.329 INFO Starting jormungandr 0.5.5 (HEAD-aec29a1, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Oct 06 11:26:03.361 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Oct 06 11:26:03.361 INFO storing blockchain in '"/tmp/jormungandr/blocks.sqlite"', task: init
Oct 06 11:26:08.813 INFO fetching block adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770, peer_address: 3.115.57.216:3000, block: adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770, task: init
Oct 06 11:26:10.139 INFO initial bootstrap completed, peer_address: 3.115.57.216:3000, block: adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770, task: init
Oct 06 11:26:11.070 INFO connecting to bootstrap peer 3.123.155.47:3000, peer_addr: 3.123.155.47:3000, task: bootstrap

Do I need to wait longer ? Or I may did something wrong when installed jormungandr via cargo ?

Thank you

**Comment by PierreLz** [comment]
Ok it worked after 40minutes of running !
