### ISSUE TITLE
return funds to faucet is not credited?

### ISSUE THREAD

**Issue by Dmindfuse** [input-output-hk/shelley-testnet#99]
**Describe the bug
I tried to return the remainder balance of my account to the faucet, but my account was not credited correctly and no apparent failure indicated. It seems only the fees have been deducted. Is the amount too large?

** Prerequisites information

1. What is your Operating system?
Ubuntu Linux (Mint)

1. What version of the jormungandr node are you using?
0.5.5

1. Did you use jormungandr installer (snap, chocolatey, brew, etc.)?
tar.gz deployment

**To Reproduce
```
 ~ $ ./send-money.sh ca1s44h5hytev8d9wty220ckglvj7ewm3yetyug8a29pu2lj5dff28sy2yf8yj 9999845600 3102 mykey
================Send Money=================
DESTINATION_ADDRESS: ca1s44h5hytev8d9wty220ckglvj7ewm3yetyug8a29pu2lj5dff28sy2yf8yj
DESTINATION_AMOUNT: 9999845600
REST_PORT: 3102
SOURCE_SK: mykey
BLOCK0_HASH: adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
FEE_CONSTANT: 1000
FEE_COEFFICIENT: 50
==================================================
## Sending 9999845600 to ca1s44h5hytev8d9wty220ckglvj7ewm3yetyug8a29pu2lj5dff28sy2yf8yj
discrimination: testing
account: mykey
 ##1. Create the offline transaction file
 ##2. Add input details
 ##3. Add output details
 ##4. Finalize the transactions
 ##5. Create the witness
 ##6. Add the witness to the transaction
 ##7. Show the transaction info
Transaction `a36225468bef2b173192a789b88709c663aef4b43146d29cc54a7b7836ca2d8f' (finalizing)
  Input:   9999846700
  Output:  9999845600
  Fees:    1100
  Balance: 0
 - 0ee5fea87358a8a84b48d857f349e22dcd19d9c8d008b1ab78fb0ad6611ff18e 9999846700
 + ca1s44h5hytev8d9wty220ckglvj7ewm3yetyug8a29pu2lj5dff28sy2yf8yj 9999845600
 ##7. Finalize the transaction and send it
2d9ec5fa6bf8fcd5daf9f253eb57657b5fa895adb790bda0e33a0991c308e438
 ##8. Remove the temporary files
  ##Waiting for new block to be created (timeout = 200 blocks = 400s)
New block was created - 964b01d813f9823c965e35da718dcd8d85b0177fbcf9d8e5b6189ddf14910a72
 ##9. Check the account's balance
---
counter: 0
delegation:
  pools: []
value: 49999845600

```

**Expected behavior
0 account balance after subtraction of fees.

**Additional context
I tried this twice, previously:
```
....
 ##7. Show the transaction info
Transaction `3859298e3d125fbfebb4aea274834ff023509253a23889ced7a548e7a1d5d534' (finalizing)
  Input:   9999847800
  Output:  9999846700
  Fees:    1100
  Balance: 0
 - 0ee5fea87358a8a84b48d857f349e22dcd19d9c8d008b1ab78fb0ad6611ff18e 9999847800
 + ca1s44h5hytev8d9wty220ckglvj7ewm3yetyug8a29pu2lj5dff28sy2yf8yj 9999846700
 ##7. Finalize the transaction and send it
cf78204f6d5d889487b33852b2d07bd2b4f18424e3c4d8883471771ec089712a
 ##8. Remove the temporary files
  ##Waiting for new block to be created (timeout = 200 blocks = 400s)
New block was created - 9ba96748968af16f616ff11915d2cb6d27753bdd863b2808f4d42aa4bb9b3b25
 ##9. Check the account's balance
---
counter: 0
delegation:
  pools: []
value: 40000000000
~ $ ./jcli rest v0 account get ca1s58wtl4gwdv232ztfrv90u6fugku6xweergq3vdt0ras44nprlccufzctpx --host http://127.0.0.1:3102/api
---
counter: 3
delegation:
  pools: []
value: 9999846700

```

**Comment by Dmindfuse** [comment]
Update:

After waiting a few more minutes it did actually update the balance:
```
./jcli rest v0 account get ca1s58wtl4gwdv232ztfrv90u6fugku6xweergq3vdt0ras44nprlccufzctpx --host http://127.0.0.1:3102/api---
counter: 4
delegation:
  pools: []
value: 0
```

However, what happened to my second (or first for that matter) attempt at transferring the entire balance? Both were submitted, both seemed to have gone through OK, but only one would have seen actual funds available. So, shouldn't it now be a negative number at least? Where can one find out if the transaction completed OK?

**Comment by dorin100** [comment]
Hi @Dmindfuse . You can check the Status of the transactions using `jcli rest v0 message logs --host "http://127.0.0.1:3102/api"`

Most probably the second transaction was not valid as the source account did not have any funds anymore.

**Comment by dorin100** [comment]
We are still working on stabilizing the network so this might be why the transaction was not included in the first new block.

**Comment by dorin100** [comment]
Hi @Dmindfuse - can we close this issue? Are there any things that are still not clear related to the initial question? Thank you.

**Comment by Dmindfuse** [comment]
@dorin100 , @jakewyo , thanks! I will try the version and bear in mind the ongoing stabilization. Thumbs up for the achievements so far! Cheers. Closing...
